### ISSUE TITLE
[1.7.10] How to divide the mod into several?

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#11]
After some refactoring (soon), I'd like to split the mod into several.
I have to divide the project into several modules that are compiled separately? Inside the current project, of course.
I don't have enough experience.

**Comment by mezz** [comment]
I don't think you should do much to the 1.7.10 branch except fix bugs.
Splitting it up will probably be complicated.

**Comment by Dream-Master** [comment]
@mezz I like to see new content in the 1.7.10 too because i am still developing on my Modpack GTNH :)

**Comment by marcin212** [comment]
[Here](https://docs.gradle.org/current/userguide/multi_project_builds.html) is example for multi-module project but I think it is not necessary for 1.7.10.

**Comment by mezz** [comment]
I have wanted to do this for Forestry for a while, to divide up the modules so that they don't crash when one is disabled. 
I'll see if I can do it, if I succeed I'll post back here.

**Comment by KorDum** [comment]
I was convinced that it is unnecessary for 1.7.10.
