### ISSUE TITLE
[1.11.2] Configurable flowers

### ISSUE THREAD

**Issue by lex1975** [ForestryMC/Binnie#112]
In the Forestry 4.2 (1.7.10) I can customize the types of flowers through a configuration file.
apiculture.cfg
flowers {
I can customize plantable flowers and accepted flowers.
I can plant a variety of flowers vie dy of other modifications that can not be duplicated by other methods.
In the versions Forestry for 1.10 and 1.11, this option was removed.

My wishes:
1. Please, inform the developer of the mod Forestry about the return of this option.
2. Add in this configuration file sections for bees from the Binnei mod.

**Comment by KorDum** [comment]
I think Forestry is not being developed. Fixing bugs in low priority and focus on the version for the game MC1.11.2.
I am only fixing the version for MC1.7.10. Therefore, in my plans, I only fix bugs and add localization support. The modification code is difficult to scale.

> Add in this configuration file sections for bees from the Binnei mod.

Hav you tried [this](https://mods.curse.com/mc-mods/minecraft/gendustry)?

**Comment by KorDum** [comment]
Forestry has own [issue tracker](https://github.com/ForestryMC/ForestryMC/issues). Please create issue with link there.
