### ISSUE TITLE
Wood Direction Bug

### ISSUE THREAD

**Issue by Radst0ne** [ForestryMC/Binnie#12]
![2017-04-17_20 47 15](https://cloud.githubusercontent.com/assets/27621272/25201925/caf9aa84-2553-11e7-84ad-f32b016ee8ad.png)
![2017-04-17_20 47 26](https://cloud.githubusercontent.com/assets/27621272/25201930/ce8f1be8-2553-11e7-8b70-341f34de9cc0.png)

Both same Wood Type (Spruce), different directions
Happens to nearly all Wood Types

**Comment by KorDum** [comment]
How to get the problem? Bug not verified.
And how is the bug related to ExtraTrees?

**Comment by Radst0ne** [comment]
The excat description is in German sorry for that, I forgot to add it here.
It just happens by placing Wood in a different direction but also to all Trees which are generated or rather cannot be replanted (because they give vanilla saplings like jungle etc.). I do not think it is related to ExtraTress because it never happens to them.
Edit: I think just the Minecraft Vanilla Wood Types are affected

**Comment by KorDum** [comment]
Mmm. Is problem in Waila?
I don't understand why this issue here...

**Comment by Radst0ne** [comment]
![](https://cloud.githubusercontent.com/assets/27621272/25100222/8451753a-23af-11e7-9691-2d4b67e4e2cb.png)
Because of this I think

**Comment by KorDum** [comment]
![image](https://cloud.githubusercontent.com/assets/1331559/25396849/d4e97520-29ee-11e7-86ec-0398b5ebc3dd.png)
I'm using pre14 + BinniePatcher (not pre15 yet, because it's in refactoring process).
What I'm doing wrong? I don't understand this issue well :)

**Comment by Dream-Master** [comment]
i compiled the new pre15 version will look if this is probaly changed.

**Comment by Radst0ne** [comment]
well then it has something to do with the modpack I think (maybe outdated version of ExtraTrees?)
Edit: ah so it has probably nothing to do with ExtraTrees :)

**Comment by KorDum** [comment]
![image](https://cloud.githubusercontent.com/assets/1331559/25397456/00dcbe4c-29f1-11e7-929f-933ade600115.png)
This is in latest build pre15.

**Comment by Dream-Master** [comment]
@Radst0ne So the visual Bug is a waila/walva bug i guess only the fence things could be a binnies mod bug?

**Comment by Radst0ne** [comment]
Im not sure if it is a binnies bug because the modpack contains the same pre14 version that KorDum tested, maybe an ID conflict?

**Comment by KorDum** [comment]
MineTweaker (or similary) added wrong recipes maybe?

**Comment by Radst0ne** [comment]
@Dream-Master removing the whole crafting recipe of the fence and readd it again should do the trick, I tried to change it in the script file but i do not know the exact id of the Extratree fence its something weird though and maybe add an recipe for the Extratree fence because they look cool? :) But i could be wrong im not so advanced with this

**Comment by Radst0ne** [comment]
I tried
recipes.removeShaped(<ExtraTrees:1026:16387>);
and then
recipes.addShaped(<minecraft:fence>)
And specified with
<minecraft:planks:*>

**Comment by labpaw** [comment]
This is waila bug which exist since forever (it happens with vanilla wood too). It is fixed in 1.11.2
https://bitbucket.org/ProfMobius/waila/issues/109/incorrect-leaves-names-again

**Comment by Radst0ne** [comment]
I think it can be closed.
Thanks to all for your amazing support 👍
