### ISSUE TITLE
[1.7.10] Crash when looking Jaded bee in Bee Database

### ISSUE THREAD

**Issue by danielrossyamitrano** [ForestryMC/Binnie#13]
I've got an ender bee from a villager, and I ran it throught my Escritorie to get her mutations. I've got the Jaded bee, but when I tryed to look up for her in the database, my game crashed.
[Here](https://pastebin.com/f9vg1EXd) is the crash report

**Comment by KorDum** [comment]
What is a database? Apiarist Database?
Judging by what I see in the pre15 code, it was fixed. Crash is not getting.

**Comment by danielrossyamitrano** [comment]
Yes, sorry. It is the apiarist database (the craftable one). I'm using, i think, the lastest versions of both forestry and binnie's mods that there are for MC 1.7.10.

I'm also using Optifine, if that means anything

**Comment by KorDum** [comment]
@zenieldanaku You using pre14 version of original mod. In pre15 this is fixed :)

**Comment by danielrossyamitrano** [comment]
@KorDum The lastest version on CourseForge is the pre14. Where is the pre15?

**Comment by Valchap** [comment]
It's on Github. You have to compile it yourself.

**Comment by danielrossyamitrano** [comment]
@valentin616 Ok, but I do not want/can/know how to do that, so I will have to live with the issue until an official release of the pre15 or whatever. Thanks anyway.

**Comment by KorDum** [comment]
Official release (from Binnie567), I think, will not, because the author has long stopped the development of mods.
Try Binnie Patcher while: https://minecraft.curseforge.com/projects/binniepatcher

**Comment by danielrossyamitrano** [comment]
I do have the binnie's patcher to run Binnie's mods with Forestry 4. But that doesn't solve the issue. Anyway, I can avoid it by not looking up that bee.

**Comment by marcin212** [comment]
@zenieldanaku You can test [this](https://ci.bymarcin.com/job/Binnie-Mods-MC1.7.10/lastSuccessfulBuild/artifact/build/libs/binnie-mods-2.0-pre15-b1.jar), but create backup first and remove binnie-patcher.

**Comment by KorDum** [comment]
@marcin212 Can we use this Jenkins for CI-builds? :)

**Comment by marcin212** [comment]
@KorDum Yes

**Comment by danielrossyamitrano** [comment]
@marcin212 yes, it worked. Thanks
