### ISSUE TITLE
[1.7.10] Crash when put scanned drone into field kit gui and take out

### ISSUE THREAD

**Issue by SihenZhang** [ForestryMC/Binnie#135]
When I put scanned drone into Field Kit GUI and take out, the GUI will change like this and crash in a while.
![GUI](http://i.imgur.com/q1bemZl.png)

Here is the crash report: https://paste.ee/p/2bFY9

**Comment by KorDum** [comment]
I don't get this crash. What am I doing wrong?

![image](https://user-images.githubusercontent.com/1331559/27396993-7ee2acd6-56bd-11e7-9f2d-25e017d3bf71.png)

**Comment by 3TUSK** [comment]
Did you try take the bee out?

**Comment by KorDum** [comment]
Yes. Crash not found.

**Comment by KorDum** [comment]
Show me `./config/forestry/modules.cfg` please. Maybe one of the modules is disabled.

**Comment by KorDum** [comment]
Check this build https://yadi.sk/d/DezRqN4u3KMHAi please
Is the problem resolved?

**Comment by SihenZhang** [comment]
It is solved when i use the build above.

**Comment by KorDum** [comment]
Ok, thanks for test.
