### ISSUE TITLE
[1.7.10] Varieties of Fragment or Grains CANNOT be used to craft gem or dust

### ISSUE THREAD

**Issue by SihenZhang** [ForestryMC/Binnie#136]
Only `Titanium Grains`, `Coal Grains`, `Blutonium Grains` and `Cyanite Grains` can be used to craft.

An interesting thing is that `Yelloium Grains` cannot be used to craft, even though it is from `Big Reactor` either.

**Comment by KorDum** [comment]
Please add MC version in future.

**Comment by KorDum** [comment]
Problem not found. Do you use custom recipes?

![image](https://user-images.githubusercontent.com/1331559/27397547-6260a124-56bf-11e7-9651-a75256ecc389.png)

**Comment by SihenZhang** [comment]
So sorry because when i delete all the MineTweaker scripts, the recipes is effective.
