### ISSUE TITLE
[1.11.2] Crop for Hops instead of Crafting recipe.

### ISSUE THREAD

**Issue by alucard87pl** [ForestryMC/Binnie#139]
Currently it's an apple with seeds, which is like making beer from wine.

**Comment by marcin212** [comment]
textures: https://img.bymarcin.com/hops.zip

**Comment by Nedelosk** [comment]
db2f4b7360c35b3c68c6c54e64cf53def603496f

**Comment by alucard87pl** [comment]
How will these be obtainable now? Grass drop? Villager Trade?

**Comment by mezz** [comment]
Grass drop sounds like a good choice.

**Comment by Nedelosk** [comment]
I have added hops as a grass seed and added a hops village field.
