### ISSUE TITLE
Fence gates always render closed when connected to cobble walls

### ISSUE THREAD

**Issue by LuigiHutch** [ForestryMC/Binnie#150]
Binnies Mods 1.11.2-2.0.0-15
Forestry 1.11.2-5.3.4.114
Forge 13.20.0.2315

Binnies fence gates always render closed, even when actually open, when they are connected to cobblestone walls. Even though they render closed you can still walk through them:
![2017-06-24_15 07 06](https://user-images.githubusercontent.com/9326429/27509195-3f200ed4-58ef-11e7-80f9-a011ac5de659.png)

**Comment by Nedelosk** [comment]
This is a forestry bug and is fixed in the newest Version.  https://github.com/ForestryMC/ForestryMC/commit/e96f4fc8a0002d30bae7de4c8b921d9671c0c1ce
