### ISSUE TITLE
[1.11.2] Binnie override Forestry cherry logs texture ?

### ISSUE THREAD

**Issue by quienti** [ForestryMC/Binnie#152]
In the world, cherry wood log have a good texture, but when I take item, it is a wrong texture

![2017-06-25_11 52 32](https://user-images.githubusercontent.com/7326954/27515778-e41c4ac6-59ab-11e7-8aea-dd017a15ee2f.png)
![2017-06-25_11 52 39](https://user-images.githubusercontent.com/7326954/27515779-e4279fac-59ab-11e7-974f-af9283b99a57.png)

**Comment by Nedelosk** [comment]
Fixed with Forestry 5.3.4.119
