### ISSUE TITLE
[1.11.2] Leaves not translate with waila

### ISSUE THREAD

**Issue by quienti** [ForestryMC/Binnie#153]
Forestry 5.3.4.114
Binnie mods 2.0.0.16 (from jenkins)
Waila 1.7.1

![2017-06-25_11 53 12](https://user-images.githubusercontent.com/7326954/27515857-da85bd88-59ad-11e7-86da-c01d28afb05a.png)

**Comment by mezz** [comment]
Waila is not updated properly any more, please try one of its replacements instead:
Hwyla, The One Probe, Fruit Phone

**Comment by quienti** [comment]
Oh, Ok, I see. I will try this night and I will give you the result
Thanks !

**Comment by Nedelosk** [comment]
It works with The One Probe:
![2017-06-26_14 13 03](https://user-images.githubusercontent.com/10259214/27538731-add28646-5a79-11e7-92db-4d5b78e04db7.png)
