### ISSUE TITLE
[1.7.10] pre 16 raspberry leaf disapear by riping

### ISSUE THREAD

**Issue by Ngar1** [ForestryMC/Binnie#165]
if rasberry bush change leafs (berries get red / ripe) -> all leafes disapeare.
Maybe because rasberry bushes have no wood.

**Comment by KorDum** [comment]
> Maybe because rasberry bushes have no wood.

and there is.
Is not a bug. This is the native behavior of the game.

**Comment by mezz** [comment]
@KorDum We can place rasberry bush leaves with the "do not decay" flag set.

**Comment by KorDum** [comment]
@mezz 
I will try to do

**Comment by Ngar1** [comment]
may be other bushes (without wood) have the same  issue, like blueberry a s o.

**Comment by KorDum** [comment]
Yes. I fixed all shrubs.

**Comment by Ngar1** [comment]
Thanks a lot!
