### ISSUE TITLE
[1.7.10] Genetics machine is not animated

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#167]
This didn't work from the very beginning of the port on Forestry 4.2.
Not show animation in progress.

**Comment by KorDum** [comment]
@mezz You were right about this :)

**Comment by KorDum** [comment]
This didn't work from the very beginning of the port on Forestry 4.2

**Comment by KorDum** [comment]
Please help.

https://github.com/ForestryMC/Binnie/blob/f969f63b6674aadcc2d34bcc67b72dfa75946e5a/src/main/java/binnie/core/machines/Machine.java#L119-L124

Earlier in the code there was such a method. But the method was not used anywhere else.
Maybe there is no some annotation?
I already broke my head...

**Comment by KorDum** [comment]
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/genetics/machine/genepool/GenepoolComponentFX.java#L28
`isInProgress` returns false only on client side

**Comment by marcin212** [comment]
@KorDum You need to add ```INetwork.TilePacketSync``` for all logic component(https://github.com/ForestryMC/Binnie/commit/3e9965b750caeb2733232a9833846b027fe6af78#diff-2578bb0b23cc8ae4f6999777fbd96e7dR16) or rewrite this: https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/core/machines/ManagerMachine.java#L44 because it doesn't check super class

**Comment by marcin212** [comment]
@KorDum  Look at 1.11.2 -> https://github.com/ForestryMC/Binnie/blob/master-MC1.11.2/src/main/java/binnie/core/machines/ManagerMachine.java#L53

**Comment by KorDum** [comment]
Thanks!

> You need to add INetwork.TilePacketSync for all logic component

Oh! That's simple!

> Look at 1.11.

Code is not finished? I don't understand this blank check.

**Comment by marcin212** [comment]
> Code is not finished? I don't understand this blank check.

@KorDum [this](https://github.com/ForestryMC/Binnie/blob/master-MC1.11.2/src/main/java/binnie/core/machines/ManagerMachine.java#L53) line is the most important. ```if``` is not needed.

Could you test code below without PR #192 :
```Java
for (Class<?> currentClass = component; currentClass != null; currentClass = currentClass.getSuperclass()) {
    Collections.addAll(interfaces, currentClass.getInterfaces());
}
```

**Comment by KorDum** [comment]
@marcin212 
```
for (Class<?> currentClass = component; currentClass != null; currentClass = currentClass.getSuperclass()) {
    Collections.addAll(interfaces, currentClass.getInterfaces());
}
```
yes, it's work.
Is this fix preferable to `add INetwork.TilePacketSync for all logic component`?

**Comment by KorDum** [comment]
I created 2 separated PR.
Can you approve right one?
#196
#192
