### ISSUE TITLE
[1.7.10] GUI of machines is not syncronized with server

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#18]
Items stay visually in the cells.
Ex. Polymeriser genetic machine and DNA Sequence inside.

**Comment by KorDum** [comment]
@ForestryMC/binnieteam can someone help me if this was fixed in 1.11.2?

**Comment by Nedelosk** [comment]
I have wixed this in 1.11.2 with this https://github.com/ForestryMC/Binnie/commit/21db702ee79501fabe08c706139b8aca4bf27301.

**Comment by KorDum** [comment]
Hmm. Forge 1.7.10 doesn't have `IContainerListener` and `Container#listeners`...

**Comment by Nedelosk** [comment]
`ICrafting` and `Container#crafters`
