### ISSUE TITLE
[1.7.10] Unnamed Machine

### ISSUE THREAD

**Issue by Ldmf** [ForestryMC/Binnie#194]
My Error or mod error

Version:

binnie mods 2.0.19
forestry 4.2.16.64

![2017-07-11_15 56 12](https://user-images.githubusercontent.com/15316448/28071844-7cd78288-6651-11e7-9287-45f7b652ca63.png)
![2017-07-11_15 56 14](https://user-images.githubusercontent.com/15316448/28071843-7cd76334-6651-11e7-8cd7-edd52f853142.png)
![2017-07-11_15 56 16](https://user-images.githubusercontent.com/15316448/28071842-7cd2a75e-6651-11e7-8344-4a65577a4bd9.png)
![2017-07-11_15 56 19](https://user-images.githubusercontent.com/15316448/28071845-7cf067b2-6651-11e7-91dc-60d0fe542744.png)
![2017-07-11_16 00 13](https://user-images.githubusercontent.com/15316448/28072056-0d694d18-6652-11e7-8383-375577ebaa0a.png)

https://github.com/GTNewHorizons/NewHorizons/issues/1648

**Comment by Dream-Master** [comment]
@KorDum Ok it seems machines are removed from the mod. So it is a issue in my Pack GTNH. 
What machines was removed from Extra Trees (meta 5,6,7,8)

**Comment by Dream-Master** [comment]
@KorDum Why Brewery, Destillery, Glass Worker, Tile Worker was removed ?

**Comment by KorDum** [comment]
@Dream-Master Only Brewery and Destillery was removed from mod for MC1.7.10 because are not finished (alchohol was removed too) and buggy.
All Workers and Lumbermill are remained available (meta 0-4).

**Comment by KorDum** [comment]
Meta was shifted due to the structure of the code mod.

**Comment by Dream-Master** [comment]
But if I type in brewery I can't find it any more in nei.

**Comment by KorDum** [comment]
Close issue if there are no more questions left please

**Comment by KorDum** [comment]
@Dream-Master Offtopic, can you (or kith) translate mod into German?

**Comment by Ldmf** [comment]
thx 4 the help
