### ISSUE TITLE
Tabs or Spaces?

### ISSUE THREAD

**Issue by mezz** [ForestryMC/Binnie#2]
This project is spaces, Forestry is tabs.
We should choose now if this project should stay spaces or become tabs.
I would like it to match Forestry, there are already mistakes where tabs and spaces are mixed.

**Comment by marcin212** [comment]
I'm fine either way.

**Comment by mezz** [comment]
Alright I'll convert everything to tabs tomorrow around this time.
Make sure you have all your changes committed, because this could make merging a bit annoying.

**Comment by Elec332** [comment]
Yep, I vote tabs :)

**Comment by KorDum** [comment]
Why tabs?
Forestry repositories contains 4 spaces.

**Comment by mezz** [comment]
Forestry is also tabs unless there is a mistake somewhere.

**Comment by KorDum** [comment]
Sorry, I looked at the code invTweaks:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/api/java/invtweaks/api/IItemTreeItem.java
