### ISSUE TITLE
[1.7.10] Wrong Coconut tree

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#20]
Bug from https://bitbucket.org/binnie567/binnie-mods/issues/383/coconut-trees

Original text:

> the coconut trees in 1.7.10 only grow to 3 high and do not give any coconuts they need to be taller

**Comment by marcin212** [comment]
We'd need to check if someone didn't add  a sapling with those properties. A small tree without fruit. It could be a crossing effect.
