### ISSUE TITLE
[1.12] [Suggestion] TechReborn Support

### ISSUE THREAD

**Issue by Skillotic0703** [ForestryMC/Binnie#208]
I remember that a long time ago, extrabees had support for Gregtech. When you update to 1.12, I would like you to support TechReborn as it's a remake of Gregtech 2.
https://ftbwiki.org/Bee_Species
You can find more informations playing FTB Ultimate but if you want I can make a spreasheet with mutations and centrifuge recipes.

**Comment by Nedelosk** [comment]
I have added back the sodalite, pyrite, bauxite, cinnabar and sphalerite bees.

**Comment by Skillotic0703** [comment]
Thank you!
