### ISSUE TITLE
[1.7.10]About missing localization and Display Errors

### ISSUE THREAD

**Issue by SihenZhang** [ForestryMC/Binnie#212]
Is this a bug that there is no info about Acclimatiser?
![1](https://i.imgur.com/hCOc1O2.png)
And when I use Analyzer the title will show Registry, when I use Registry the title will show Analyzer just like this.
![2](https://i.imgur.com/jOuZy3V.png)
![3](https://i.imgur.com/i4eVj3w.png)

**Comment by KorDum** [comment]
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/resources/assets/genetics/lang/en_US.lang#L125
Missed localization for en_US. Can you help us with text?

**Comment by KorDum** [comment]
> And when I use Analyzer the title will show Registry

This is right.

> when I use Registry the title will show Analyzer

And this is wrong. Thanks for report!

**Comment by KorDum** [comment]
> The Analyser takes breedable individuals and DNA sequencers and analyses them to determine the genes present. This requires DNA Dye, created from purple dye and glowstone

In `en_GB.lang` pre14 version

**Comment by KorDum** [comment]
Thanks for report!
