### ISSUE TITLE
Replace Tab with a saner hotkey

### ISSUE THREAD

**Issue by AnrDaemon** [ForestryMC/Binnie#216]
Binnie uses "Hold Tab for tooltips", which forces the user to invoke inane tricke to activate the feature, when Tab key is already used for other actions. For example, to open Inventory.

Can this be changed to a more sane hotkey? F.e. "Crouch" key like other mods using.

**Comment by KorDum** [comment]
For MC 1.11.2 or 1.7.10?
We don't add new features for 1.7.10 anymore. Only bugfixes and localization.

**Comment by AnrDaemon** [comment]
TTTT, I consider it a bug.

**Comment by mezz** [comment]
I think tab was chosen because shift is used to show extra information on the items in the slots already.
On the latest version we should make it a configurable hotkey using the GUI context.

**Comment by KorDum** [comment]
Yes, I don't think this is a bug. Any other key will conflict with the same or something else. There should be a setting, but for MC1.11.2 (1.12), because for MC1.7.10 it's a feature.

**Comment by AnrDaemon** [comment]
> I think tab was chosen because shift is used to show extra information on the items in the slots already.

I'm failing to see, how "Information on items in the slot" conflicts with "information about UI elements".

**Comment by KorDum** [comment]
Because if you need shift for additional info of bees...
![image](https://user-images.githubusercontent.com/1331559/28404375-bc02b6a8-6d31-11e7-997a-df2e88bbc8dd.png)

But you can see this...
![2](https://user-images.githubusercontent.com/1331559/28404454-0dbd27bc-6d32-11e7-9e13-afe77d26db02.jpg)

**Comment by AnrDaemon** [comment]
Shouldn't that appear on an empty slot only?…

**Comment by KorDum** [comment]
Unfortunately, due to the fact that Binnie wrote his custom GUI, any improvements to it can incur a lot of edits in other places. This improvement can be made for 1.11.2 (1.12).

**Comment by AnrDaemon** [comment]
Thanks for clarification.

**Comment by mezz** [comment]
I made some changes today so that basic help is shown on empty slots. 
Advanced help is shown when holding the Tab key, which is now configurable in the controls. It is also enabled when you have advanced tooltips on.
