### ISSUE TITLE
[1.7.10] Artifact "B" in tooltips

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#22]
It is necessary to understand and remove the letter "B" from tooltips

![image](https://cloud.githubusercontent.com/assets/1331559/25433771/3cba397a-2a92-11e7-94c3-8b68404ad149.png)

**Comment by KorDum** [comment]
Hmm. Is this bug in forestry forestry_1.7.10-4.2.16.64-dev.jar ?

**Comment by marcin212** [comment]
I think that is a decompilation artifact. Probably a text formatting character (paragraph?) probably one of these: [Link](http://minecraft.gamepedia.com/Formatting_codes)

**Comment by KorDum** [comment]
Yes, this is repaired by deleting the paragraph character.

**Comment by KorDum** [comment]
Sorry, this commit for 23 issue, not 22. My mistake.

**Comment by KorDum** [comment]
Can I close this issue?
