### ISSUE TITLE
Extra Trees Missing

### ISSUE THREAD

**Issue by marikc0** [ForestryMC/Binnie#225]
The mod is installed on 1.7.10 on the server with the latest mod file (2.0.19). I noticed that Extra Trees is missing some things. When searching in NEI for extra trees blocks and items there are a lot of blank blocks (with no textures) listed for the Extra Trees saplings, etc. Extra Bees and the rest seems to be fine. I'm not really sure how to provide the right information for this though.  Let me know.

**Comment by KorDum** [comment]
Can you show me screenshot?
Alchohol and alchohol machines was removed from pre15 version.
If you uses custom recipes with it, you may see any wrong blocks.

**Comment by marikc0** [comment]
I seem to have fixed it. You can close this. Sorry about that.
