### ISSUE TITLE
[1.7.10] Add Nei support

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/Binnie#226]
Some fluids like bacteria dont have any recipe shown in Nei because the machine not have any NEI interface. @KorDum are you planing to add some for make it easier to understand how thing work?

**Comment by KorDum** [comment]
I can try to make it, if @Nedelosk or @mezz don't mind this improvement.

**Comment by mezz** [comment]
I would prefer we put our effort into the latest version. 1.7.10 Binnie's has hundreds or thousands of downloads from players, I expect the latest version will easily have 100 times more people playing. Feel free to make an addon mod to add NEI integration for Binnie's in 1.7.10, but please keep this in mind.

**Comment by Dream-Master** [comment]
I dont have that experience to do it by my self i guess.

**Comment by KorDum** [comment]
I sent private message to @bdew (neiaddons author) and asked for access to the source code.

**Comment by mezz** [comment]
His mods are all open source, you can see it here https://github.com/bdew/neiaddons

**Comment by KorDum** [comment]
Oh, I missed this.
I'll try to do in my spare time.

**Comment by bdew** [comment]
NEI Addons never added machine recipes, you might be thinking of [NEI Plugins](https://bitbucket.org/mistaqur/nei_plugins/wiki/Home)
