### ISSUE TITLE
[1.7.10] Alvery has no name

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/Binnie#227]
![image](https://user-images.githubusercontent.com/2970688/28570508-a79c4236-713e-11e7-88b7-f812896f36cf.png)
![image](https://user-images.githubusercontent.com/2970688/28570512-ab78d932-713e-11e7-941f-71ce0091069c.png)
Alvery 1-4

tested with last available source

**Comment by KorDum** [comment]
It's not binnie blocks. Check renaming in custom recipes please.

**Comment by Dream-Master** [comment]
Ok i dont rename them in my custom recipes maybe a bug or the involvment of other mods in my GTNH Pack. I not change Forestry version for a long time. 

A sulution could be readd the name with Minetweaker but i dont understand why they be renamed.

**Comment by Dream-Master** [comment]
Forestry not have a Block that named Mutatron

![image](https://user-images.githubusercontent.com/2970688/28571133-b7e5d0c8-7141-11e7-96df-c710a94d42e9.png)
When i look in the localizer i see meta id 3 
tile.for.alveary.3.name=Alveary Fan

**Comment by KorDum** [comment]
It's Forestry block "Fan". Binnie doesn't have it. Only "Mutator" (to left of this).
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/resources/assets/extrabees/lang/en_US.lang#L194
Check MineTweaker scripts please.

**Comment by Dream-Master** [comment]
Sure i know. I know it is a Forestry Block and forestry not change anything for a long time. Can it be a issue from Binnies side change the way lacalizers are made or changed. With old binnies version and binnies fixer i am not see this issue thats why i ask here.
And yes i checked Minetweaker scripts and i dont have any entry to change this names.

**Comment by Dream-Master** [comment]
I doing now a duct tape fix and rename the blocks to his original names via Minetweaker.

https://github.com/GTNewHorizons/NewHorizons/commit/85ae55fca6cf873a8ff644564159eab73beeb63c

**Comment by KorDum** [comment]
Lang files of Binnie not overrides Forestry lang. Check them yourself.

I checked - nothing:
![image](https://user-images.githubusercontent.com/1331559/28571549-0e5c8b86-714c-11e7-9c7f-1be00f369837.png)

**Comment by Dream-Master** [comment]
wired! Ok my minetweaker script will works and i dont find any entry in my forge log. One of those mysterious bugs.

**Comment by KorDum** [comment]
This is magic, yeah o_O

**Comment by draknyte1** [comment]
It's a GT++ issue.
