### ISSUE TITLE
[1.7.10] Crash with V2.0.19

### ISSUE THREAD

**Issue by SilverKytten** [ForestryMC/Binnie#228]
'Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: binnie.genetics.Genetics'

[crash-2017-07-25_08.02.50-client.txt](https://github.com/ForestryMC/Binnie/files/1173207/crash-2017-07-25_08.02.50-client.txt)

**Comment by KorDum** [comment]
Update your Java to 1.8

**Comment by SilverKytten** [comment]
I'm unable to run Minecraft with Java 8. :| Is there any workaround for 7?

**Comment by KorDum** [comment]
No, source compatibility with 1.8 only
https://github.com/ForestryMC/Binnie/blob/master-MC1.11.2/build.gradle#L16
