### ISSUE TITLE
[1.11.2]Game Crash from looking at wood in JEI

### ISSUE THREAD

**Issue by BluMasc** [ForestryMC/Binnie#229]
version: 2.1.0.8

When looking at the wood types in JEI the game crashes with this error:
[errorlog.txt](https://github.com/ForestryMC/Binnie/files/1184782/errorlog.txt)

this is a instance with almost 140 mods, so i'm not sure if it's realy on your part, but it only happens on your wood types.

**Comment by mezz** [comment]
Thanks for the report!
