### ISSUE TITLE
[1.11.2] Crash when re-entering a world

### ISSUE THREAD

**Issue by Xiaminou** [ForestryMC/Binnie#231]
Crash when re-loading a singleplayer world, happens every time but not for every world.

Crash Report: [crash-2017-07-29_20.19.59-server.txt](https://github.com/ForestryMC/Binnie/files/1185139/crash-2017-07-29_20.19.59-server.txt)
**mezz edit**: https://gist.github.com/mezz/2983889706ec3d231b378806c82fd8da

Environnement: Singleplayer
Minecraft: 1.11.2
Binnie's: 2.1.0.8
Forestry: 5.3.4.152
Forge: 2425
Modlist: [list.txt](https://github.com/ForestryMC/Binnie/files/1185137/list.txt)

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue with Industrial Foregoing.
Please report to them here and link back to this issue: https://github.com/Buuz135/Industrial-Foregoing/issues

**Comment by Xiaminou** [comment]
Fixed
