### ISSUE TITLE
[1.7.10] Launch Crash

### ISSUE THREAD

**Issue by ghost** [ForestryMC/Binnie#237]
I get this error message

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: binnie/extrabees/apiary/ItemHiveFrame

For the bees stuff i have binnie's Mods, BinniePatcher, magic bees..

**Comment by KorDum** [comment]
Please write version of mod and MC in future.

**Comment by KorDum** [comment]
https://github.com/ForestryMC/Binnie/issues/224
