### ISSUE TITLE
Disabling extrabees doesn't work

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/Binnie#243]
Forge: forge-13.20.1.2393
Forestry: forestry_1.11.2-5.3.4.155
Binnie's Mods: binnie-mods-1.11.2-2.1.0.34
Issue: Setting the extrabees module to false in the binnie'smods config file doesn't actually disable the module and loads up as normal.

**Comment by Nedelosk** [comment]
Duplicate of #305
