### ISSUE TITLE
Crash when disabling extratrees module

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/Binnie#244]
Forge: forge-13.20.1.2393
Forestry: forestry_1.11.2-5.3.4.155
Binnie's Mods: binnie-mods-1.11.2-2.1.0.34
Crashlog: https://pastebin.com/X4Xaq5xf

**Comment by Nedelosk** [comment]
@whitestarx0312 Can you please test if this is fixed in the newest version ?

**Comment by mezz** [comment]
This is probably still broken, the module separation is not completely correct yet.

**Comment by jjc54** [comment]
Hmm so I tested with only extra trees disabled and I'm no longer getting the same crash, but I do get a new one.
https://gist.github.com/whitestarx0312/ea881e4fca87ddacad78e8bf4095d605
Please let me know if you'd like me to start a new issue for this.
