### ISSUE TITLE
1.7.10 Arborist database doesn't show resultant mutations

### ISSUE THREAD

**Issue by Owlblocks** [ForestryMC/Binnie#247]
![2017-08-04_17 24 41](https://user-images.githubusercontent.com/26911009/28991189-e076ce98-7939-11e7-9032-e58d6e5fce8c.png)
![2017-08-04_17 24 33](https://user-images.githubusercontent.com/26911009/28991190-e079fe74-7939-11e7-8041-614842e9fca8.png)

When looking at tree species in the arborist's database, "discovered species" is displayed instead of the species used to breed. NOTE originally I found this bug in pre-14, looked it up, found the stable 20 release, and updated. The bug doesn't seem to be fixed, however.

**Comment by Owlblocks** [comment]
![2017-08-04_17 28 03](https://user-images.githubusercontent.com/26911009/28991214-50ecbed0-793a-11e7-9815-fb556d6e4615.png)

A similar issue is with the further mutations section. Only the selected tree is shown, when further mutations were discovered.

**Comment by KorDum** [comment]
I do not understand the problem.
The resulting mutations show how to get the selected tree.
Resulting mutations show where the selected tree still participates.

**Comment by mezz** [comment]
I think they mean that the tooltip should show the name of the tree, instead of saying "Discovered Species"?

**Comment by Owlblocks** [comment]
That's correct. Both the graphic and the tooltip don't show the trees involved in the mutation. For instance, if you see the pecan sapling picture, it shows "discovered species", when that's obviously a discovered method of breeding pecan (because it's the only one). Being able to see what got me where and what trees I've already bred together are the features I'm missing, and they're supposed to be there :/ thanks for the speedy reply, and I hope I've helped clarify. Big fan of the mods, and it's great they're still being actively supported.

**Comment by KorDum** [comment]
Fixed in next release
