### ISSUE TITLE
Classification conflict with forestry on 1.11

### ISSUE THREAD

**Issue by DaKingCartoon** [ForestryMC/Binnie#248]
simply put, the error is:

> Caused by: java.lang.RuntimeException: Could not add new classification 'genus.bees.aquatic', because the key is already taken by forestry.apiculture.genetics.BranchBees@72aa417d.

**Comment by Nedelosk** [comment]
This is not a conflict on our side. This is a bug from More Bees. https://github.com/Lach01298/MoreBees/issues/55
