### ISSUE TITLE
[1.7.10] Blacked GUI sometimes

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#25]
Bug from https://bitbucket.org/binnie567/binnie-mods/issues/327/genepool-gui-rawdna-and-power-black-out

Original text:

> The RawDNA and Power GUI bars go black when the genepool is in use. Hovering mouse cursor over the RawDNA tank renders both back to normal but as soon as you move off the RawDNA tank they go black again.

**Comment by KorDum** [comment]
More problems with GUI. Maybe drop it and use existing forestry GUI classes?

**Comment by KorDum** [comment]
If remove the tank output component, the problem disappears.
I don't know why this happens. I tried to resave (and optimize) the assets. Nothing.

**Comment by mezz** [comment]
The OpenGL states for drawing fluids, backgrounds, and icons is slightly messed up. I fixed it in the 1.11 branch I think, you can compare the gui drawing code.

**Comment by KorDum** [comment]
I see that there are a lot of OpenGL fixes in 1.11.2.
Unfortunately, I don't understand OpenGL at all...
I try it later.
