### ISSUE TITLE
[1.12] Game crashes when you open GUI on some blocks 

### ISSUE THREAD

**Issue by DehFelix** [ForestryMC/Binnie#253]
Some blocks  when you right click make the game crash I've tested a few and some blocks with GUI don't crash (like the distillery) but a lot are, some that do cause the game to crash are:

Woodworker/Glassworker/Planeworker/Tileworker : https://pastebin.com/b8CiM3VF
Isolator : https://pastebin.com/Lw6N3p0D

Minecraft : 1.12
Forge : 12.21.1.2443
Forestry :1.12-5.5.0.154
Binnie : 1.12-2.2.0.3

**Comment by mezz** [comment]
Thanks for the report!

**Comment by DehFelix** [comment]
I tested on 1.12-2.2.0.5 and most of the crashes have been fixed, but the Analyst and Registry are crashing the game when you try to analyse a bee with the Analyst and when you click on a bee no the Registry.

Crash logs:
Analyst: https://pastebin.com/udHcY9DZ
Registry: https://pastebin.com/Aqnwdf3E

I'm posting it here since they have apparently the same erro as before: "java.lang.IllegalStateException: Tried to get sprite before it is registered."

**Comment by mezz** [comment]
Thanks, looks like I missed some.
