### ISSUE TITLE
Blocks/Items persistent in JEI after module disabled

### ISSUE THREAD

**Issue by jjc54** [ForestryMC/Binnie#254]
Forge: forge-14.21.1.2420
Forestry: forestry_1.12-5.5.0.154
Binnie's Mods: binnie-mods-1.12-2.2.0.3
Issue: Blocks/items stay in JEI, albeit completely white, even after I disable Botany.
Screenshot of JEI: http://imgur.com/a/fLvLu

**Comment by mezz** [comment]
Thanks for the report!

**Comment by Nedelosk** [comment]
@whitestarx0312 Can you please test if it is fixed in the newest version ?

**Comment by jjc54** [comment]
Can confirm this is fixed, thanks!
