### ISSUE TITLE
[1.7.10] More Arborist's Database Glitches

### ISSUE THREAD

**Issue by Owlblocks** [ForestryMC/Binnie#256]
This is more of a part two to some problems with the arborist's database. After updating, the name of the sapling displayed properly, as asked. However, one glitch mentioned (albeit, I'll admit, briefly), that the icons were also not working, was not. However, this is a minor error as the saplings can be identified anyway. However, the fix brought new issues. Now, the name of the sapling always displays, whether you've unlocked that route or not. 
![2017-08-07_18 47 21](https://user-images.githubusercontent.com/26911009/29099564-04a88fc6-7c5b-11e7-9d78-551c31ab82c4.png)
![2017-08-07_18 47 30](https://user-images.githubusercontent.com/26911009/29099563-04a893d6-7c5b-11e7-9776-9476089d6779.png)
Notice in the first picture that 1) the papaya sapling isn't rendering properly, and 2) the tree the sapling is being crossed with (jungle) in the further mutations category is undiscovered. That is, the resultant and further mutations are displaying whether that route or even the resultant tree was discovered or not. If there's any clarification needed (I'm unused to doing bug reports; this mod has really gotten me excited about helping in the development process, especially because I'm working on treebreeding so much in my modded world) I'll be happy to provide it.

**Comment by KorDum** [comment]
Thanks for report!
I'll see this problem in the near future and try to fix it.
