### ISSUE TITLE
[1.7.10] WAILA and Thaumcraft compatibility errors

### ISSUE THREAD

**Issue by Owlblocks** [ForestryMC/Binnie#257]
These are two issues I'm not sure are related, although they might be They also might be on the WAILA and thaumcraft sides, although I don't think so. I'm also unsure if this is the proper place for cross-mod compatibility, but I'm not sure the errors are exclusively with those mods (Like I said, they might be related even to each other). The problem with WAILA is that every extra trees log is labelled as "Apple Wood" and every planks block is labelled as "Fir wood planks". These problems are not the case with forestry.
![2017-08-08_17 07 04](https://user-images.githubusercontent.com/26911009/29099765-3379ee7a-7c5c-11e7-8912-94e49297f356.png)
![2017-08-07_18 57 07](https://user-images.githubusercontent.com/26911009/29099767-337af39c-7c5c-11e7-9f6b-0c3bb46fbefc.png)
The other error (not pictured, because it's easily describable) is that extra trees log blocks (maybe planks, too, I haven't checked) do not drop as items when broken with a thaumcraft axe of the stream. They break correctly, with the farthest block first, but don't drop in item form.

**Comment by KorDum** [comment]
@mezz @Nedelosk What do you think about it?
Need to enter the integration with WAILA in the Binnie?

**Comment by mezz** [comment]
Forestry in 1.7.10 worked around this issue somehow but I remember it was a pain... but maybe waila simplified it later.
First try fixing all the pick-block methods, I think that the latest waila on 1.7.10 uses that to get the item stack, and then gets the name from there.

**Comment by KorDum** [comment]
Ok, I'll look it up.
