### ISSUE TITLE
[1.7.10] Compartment dupe bug

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#26]
Bug from https://bitbucket.org/binnie567/binnie-mods/issues/267/compartment-dupe

Original text:

> There is a dupe with Compartments (All types), where if someone is to place an item in the compartment, and stay looking in the GUI. Someone else is able to break the compartment, but the person in the GUI can take the item out, and the person who broke it will have the items inside. Thus duplicating items.

**Comment by KorDum** [comment]
At all Binnie machines, not only Compartment...

**Comment by Elec332** [comment]
Should no longer happen in alveary parts in 1.11

**Comment by KorDum** [comment]
@Elec332 What can you advise to fix this bug in 1.7.10?

**Comment by Nedelosk** [comment]
@KorDum I have fixed this issue in 1.11.2. ae1168ea60259f22b211e171c3dd19c959e8055b

**Comment by KorDum** [comment]
@Nedelosk thanks! I will look in the near free time
