### ISSUE TITLE
[1.12] Ceramic block issues

### ISSUE THREAD

**Issue by Copedizzle** [ForestryMC/Binnie#261]
Two issues arise when trying to use colored ceramic blocks. These issues do not apply to patterned ceramic blocks.

1. If a ceramic block is in my inventory and I try to get a different colored ceramic block from JEI, it gives me the same colored block that is already in my inventory. It will only give me the correct color when the original block has 64 stacks or I remove the original color from my inventory. 
Pictures for reference:
![2017-08-12_16 36 07](https://user-images.githubusercontent.com/30962400/29244118-57149a22-7f7e-11e7-92bb-1630408576a5.png)

![2017-08-12_16 36 23](https://user-images.githubusercontent.com/30962400/29244119-5d585fcc-7f7e-11e7-800c-69e15819dcc2.png)

2. Regardless of the color of the ceramic block placed in the world, when I log out and back in to the game, every colored ceramic block becomes an aquamarine ceramic block.
Pictures for reference:
Before logging off: 
![2017-08-12_16 36 36](https://user-images.githubusercontent.com/30962400/29244121-6603f366-7f7e-11e7-98a5-8e95375fb4c3.png)

Logging in: 
![2017-08-12_16 37 28](https://user-images.githubusercontent.com/30962400/29244122-6c0cf21c-7f7e-11e7-882a-64045998c8d5.png)

**Comment by Nedelosk** [comment]
Thanks for the report!
Fixed in the next build.
