### ISSUE TITLE
Missing Bottle Model Pixels

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/Binnie#262]
![2017-08-12_22 53 25](https://user-images.githubusercontent.com/10259214/29244142-629c4fa6-7fb1-11e7-9289-69fb3f240679.png)

**Comment by mezz** [comment]
Hm I couldn't figure this out. The bottle assets in Forestry look fine. I think there may be something odd with the forge bucket render logic?

**Comment by mezz** [comment]
@nstearns96 what was the issue causing this bug?

**Comment by nstearns96** [comment]
To be honest I really don't know. I tried all sorts of things modifying the forestry texture and got some very weird results. I ended up just putting a custom asset into Binnie's, using that, and it worked perfectly the first time. If I had to guess it was some sort of transparency issue in the forestry asset.

**Comment by mezz** [comment]
Cool, I figured as much but was holding some hope that you might know. What a weird bug...
