### ISSUE TITLE
It Crashes (game won't start) MC1.12 Forge 2443

### ISSUE THREAD

**Issue by ghost** [ForestryMC/Binnie#263]
[crash-2017-08-14_10.05.51-client.txt](https://github.com/ForestryMC/Binnie/files/1221476/crash-2017-08-14_10.05.51-client.txt)
hope crash report tells everything

binnie-mods-1.12-2.3.0.26

**Comment by trilexcom** [comment]
same for us too 

https://pastebin.com/GppHWYFE

Forge: 2443
Forestry Version : forestry_1.12-5.5.0.163
binnie-mods-1.12-2.3.0.26

**Comment by asiekierka** [comment]
Same here. 2.3.0.22 works fine, 2.3.0.27 crashes, have not tested other versions.
