### ISSUE TITLE
1.12.1(binnie's mod downloading forestry for 1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [ForestryMC/Binnie#268]
i updated to binnie-mods-1.12-2.3.0.29 and it grabbed a version of forestry for 1.10.2 thought id let you know

**Comment by mezz** [comment]
Thanks for the report!
I'm not sure what you mean. We do not download anything, you have to download the mods yourself. Can you explain?

**Comment by SDUBZ** [comment]
it grabbed its dependancy from curse and it grabbed a version of forestry for 1.10.2 but i fixed it manually just thought ti was weird it grabbed it for 1.10.2 not 1.12

**Comment by mezz** [comment]
I think this is a Curse issue, can you report it to them?
We do not specify a version of Forestry, so if it picked 1.10.2 then there is a bug with Curse.
