### ISSUE TITLE
Right clicking on Isolator crashes client 

### ISSUE THREAD

**Issue by Tejasminer** [ForestryMC/Binnie#271]
Modpack All the mods 3.
Binnies version 1.12-2.2.0.3

[crash-2017-08-15_22.17.49-client.txt](https://github.com/ForestryMC/Binnie/files/1226981/crash-2017-08-15_22.17.49-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/Binnie/issues/253
Please update to the latest version, it is fixed there.
