### ISSUE TITLE
[1.12.1] Trees with a 2x2 or higher girth don't spawn correctly 

### ISSUE THREAD

**Issue by DehFelix** [ForestryMC/Binnie#278]
Saplings from Extra Trees with a 2x2 or higher girth don't spawn correctly, this happens if the sapling has the higher girth normally or if you change via serum or the genesis item.

![2017-08-18_22 22 19](https://user-images.githubusercontent.com/23126128/29482287-01186ff4-8465-11e7-8e67-24837d740f76.png)

![2017-08-18_22 22 29](https://user-images.githubusercontent.com/23126128/29482290-0d437d00-8465-11e7-85b3-8b348889e725.png)

They will for some reason spawn correctly if you use bone meal on the sapling in the N-W conner, for 2x2, but if you use the bone meal on any other sapling they won't spawn correctly.

- Minecraft : 1.12.1
- Forge : 14.22.0.2456
- Forestry :1.12-5.5.0.169
- Binnie : 1.12-2.3.0.32

**Comment by mezz** [comment]
Thanks for the report!
This was an issue in Forestry a long while ago, we can probably copy the logic from there.

**Comment by leagris** [comment]
Just had the exact same issue with Great Cedar same as illustration above.
Trees grows off 1 block south on positive x,z coordinates.
