### ISSUE TITLE
[1.12] - binnie-mods-1.12.1-2.3.0.34 not compatible with 1.12

### ISSUE THREAD

**Issue by Protheus** [ForestryMC/Binnie#279]
binnie-mods-1.12.1-2.3.0.34 is not compatible with 1.12

forge: 2443

![image](https://user-images.githubusercontent.com/1455178/29483895-c1dde474-84b2-11e7-8609-2628e9c605a9.png)

**Comment by mezz** [comment]
Oops, thanks.

**Comment by mezz** [comment]
Should be fixed in the next release by this change https://github.com/ForestryMC/Binnie/commit/3fc36f8e37dba601588610a6b675a670953f5aee

**Comment by Protheus** [comment]
sweet, tnx
