### ISSUE TITLE
Acclimatizer crashes game causes no change in bee

### ISSUE THREAD

**Issue by evanthelynn** [ForestryMC/Binnie#282]
I have started playing around with the acclimatizer in order to bring nether bees to the overworld, and have encountered two problems, 1) it does not seem to work * and 2) when you use tab to look at the functions of each slot, the client crashes.

# correction! I have experienced block existence toxicity, I had moved the acclimatizer away from it's power source in an attempt to troubleshoot the tab problem and even without looking at the GUI, it crashed my game. I have broken it and destroyed the acclimatizer block and the four bees I have put through it and have not crashed yet.

## Context

We're playing on forge 13.2.1.2454
We have mincraft 1.11.2 intalled
We have the following mods installed -
https://gyazo.com/27e703925c354fcd99f0ccde53a31334
https://gyazo.com/b23c20dac54c7c8657ea5925d505d360
https://gyazo.com/ebcf190cd7639af1ad9bfd818f37e0e1
https://gyazo.com/7ebd244a74cce301ef36638e156241f6
I was able to access the tab screen twice yesterday, with an attempt between that caused a crash
I can enter the screen and exit it without tab and I have not seen a crash
I used the machine overnight as described in * and it is now tab-toxic.
I have debug turned on to monitor frame life

*I moved the machine several times
Attempted between three different nbt drones and a princess, all of sinister homo-type
I increased power through two different mods - rftools and extra utilities 2
I attempted a change on internal battery
I attempted changes in the overworld and the nether
I attempted temperature and humidity changes with snowballs and water capsules and water cans
When I read that it can take a -lot- of items, I automatically pumped in ~2.3k of water cans into the back of it overnight, preceding the tab-toxicity
There was no change in the bees that I could see in either the temperature attempts or the humidity attempts.

I hope I gave you enough information to work with, this is my first bug report ever.

**Comment by mezz** [comment]
Thanks for the report!
I'm not exactly sure what you are saying, I actually need less information I think :).
Please put your crash log on https://gist.github.com/ and link it here, that will help me understand better.

**Comment by Nedelosk** [comment]
Close this because of no answer
