### ISSUE TITLE
[1.7.10] Extra Trees - Missing OreDict entries for fruits

### ISSUE THREAD

**Issue by cheesealmighty** [ForestryMC/Binnie#283]
This is a minor issue, but some of the fruits added by Extra Trees is missing their oredict entries, while some do; and this is making them incompatible with other mods (mainly Harvestcraft). 

I'm aware I can add recipes/oredict entries through minetweaker, but just wanted to let you know.

Also adding already existing ones into listAllnut/listAllfruit wherever applicable would be much appreciated too.

**Comment by cheesealmighty** [comment]
Here's a minetweaker script adding every missing fruit into the oredict similar to the harvestcraft style, if anyone comes looking for this:
https://paste.ubuntu.com/25357683/

**Comment by cheesealmighty** [comment]
I don't think I can make a pull request, but I updated the part missing, as far as I understand it. 
https://paste.ubuntu.com/25362906/

It's the code here: https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/extratrees/item/Food.java

Can add the default forestry fruits to the "listAllfruit"/"listAllnut" etc, if this is helpful for you?

Edit: I forgot your code was adding the prefix later. Also didn't forget at the same time, somehow. _Well that was a waste of my time._ Oh well.

**Comment by RusTit** [comment]
@mezz I understood the problem, the author's suggested variant is correct? Should I make a PR?

**Comment by mezz** [comment]
Looks good to me, it looks like they have done a careful job of finding the right oredict names.
I doubt anything except harvestcraft uses those but it will be nice for anyone using it.
