### ISSUE TITLE
[1.12] Hives show as 1 with a missing texture

### ISSUE THREAD

**Issue by adrwa** [ForestryMC/Binnie#284]
In JEI when searching hive, you see 1 extra bees hive with a missing texture, then if you look for uses (and you have one of the addons installed) it shows all the hives uses as if it was just 1 hive.

**Comment by mezz** [comment]
Thanks for the report!
I was able to fix the issue where JER treated all the hive as the same in JEI.

I'm not able to reproduce the missing texture issue with just Binnie's, Forestry, JEI, and Forge.
Please try to find which mod is causing the conflict.

**Comment by mezz** [comment]
This doesn't seem to happen any more.
