### ISSUE TITLE
Compartment Crash on Opening

### ISSUE THREAD

**Issue by acemagex** [ForestryMC/Binnie#290]
[crash-2017-08-25_20.57.58-client.txt](https://github.com/ForestryMC/Binnie/files/1253388/crash-2017-08-25_20.57.58-client.txt)
Crafted and placed a standard compartment, opened it, and immediately crashed. Waila perhaps? #

**Comment by acemagex** [comment]
Mezz, I just want you to know, I hugely appreciate what you do. The fact that this was posted and fixed in around 3 hours is astounding.

**Comment by mezz** [comment]
Thanks!
