### ISSUE TITLE
Binnie 2.3.0.44 crashes with Forestry 5.5.0.176

### ISSUE THREAD

**Issue by asiekierka** [ForestryMC/Binnie#291]
http://paste.asie.pl/Q9UF

Earlier versions of Forestry do not exhibit the problem; newer versions of Binnie's do not compile.

**Comment by Ushupiuck** [comment]
Additionally, if you go into the jar and remove the "extratrees" folder/module by hand, the game loads correctly with zero errors or crashes. Found out while experimenting... It's not something a user should do, I know... but meh, I just followed my instincts, @Nedelosk 
Thanks for reading, and keep going forwards!

**Comment by mezz** [comment]
Thanks, this is a known issue but the build server is having issues. 
Gradle crashes when building Binnie's so I've been focused on that.

**Comment by mezz** [comment]
I pushed a manual build that has the fix for this.
The build server gradle issue is a JVM crash on Linux and I reported it to Oracle, ugh.

**Comment by brisingraerowing** [comment]
@mezz Having had to deal with Oracle Java bug reports before, I feel your pain.
