### ISSUE TITLE
Binnie 2.3.0.44 crashes in 1.12.1

### ISSUE THREAD

**Issue by mcfilmmakers** [ForestryMC/Binnie#292]
Running in Forge 2459: [https://paste.ee/p/LfcKV](https://paste.ee/p/LfcKV)

**Comment by mcfilmmakers** [comment]
2.3.0.35 also seems to crash. My guess is because of the new forestry version?

**Comment by ghost** [comment]
Did you look at the issues before posting?

https://github.com/ForestryMC/Binnie/issues/291

Reported 8h ago.

**Comment by Nedelosk** [comment]
Duplicate of #291
