### ISSUE TITLE
[1.12] Extra Trees fruits have excessive saturation

### ISSUE THREAD

**Issue by Lykrast** [ForestryMC/Binnie#294]
Binnie's mods version : 1.12.1-2.3.0.54

Fruits added by Extra Trees have an exceedingly high saturation modifier of [3.0](https://github.com/ForestryMC/Binnie/blob/master-MC1.12/extratrees/src/main/java/binnie/extratrees/items/ItemETFood.java), which looks like that with AppleSkin (to view the actual values, saturation is the lower bar) :
![image](https://user-images.githubusercontent.com/8684850/29751556-430a5922-8b4f-11e7-93b3-61107a485291.png)

Which is a stark contrast to Forestry's fruits which have a [0.2](https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/core/items/ItemFruit.java) modifier which looks like this :
![image](https://user-images.githubusercontent.com/8684850/29751596-f44d9fe6-8b4f-11e7-94e6-dfafacac5d55.png)

Or even to vanilla food :
![image](https://user-images.githubusercontent.com/8684850/29751605-0fa8cc2a-8b50-11e7-9e8d-08bf27fbbcd8.png)

**Comment by mezz** [comment]
Thanks, that's pretty unbalanced.
