### ISSUE TITLE
(1.12.1) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [ForestryMC/Binnie#295]
Hi ! I love your mod, but... poof! crashes just before the 3/7 :/
[crash-2017-08-27_19.29.36-client.txt](https://github.com/ForestryMC/Binnie/files/1254579/crash-2017-08-27_19.29.36-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
You're on Binnie's 2.3.0.44, please update to 2.3.0.54 where this bug has been fixed.

**Comment by Migmag789** [comment]
Oh, thank you ^^
