### ISSUE TITLE
(1.12.1) Crash with parts of Binnie's Mods disabled

### ISSUE THREAD

**Issue by thestarlion** [ForestryMC/Binnie#296]
[crash-2017-08-28_12.56.55-client.txt](https://github.com/ForestryMC/Binnie/files/1256683/crash-2017-08-28_12.56.55-client.txt)

I only wanted the bees, since the other parts have nothing to interest me and I can't just load Extra Bees by itself, so I disabled the other three modules in the binnie-mods.conf file in the forestry folder. Attached crash report ensued.

**Comment by mezz** [comment]
Thanks for the report!
We're working on separating the modules better so they can be properly disabled. It may be a while before the code is in a good enough state for it to be possible, but we are making good progress.

**Comment by Zygus42** [comment]
This is a related issue, although not a crash - with Genetics turned off in the config (B:genetics=false), you still get all the info on the genetics machinery in JEI if you look at a bee with Use (U).
