### ISSUE TITLE
conflict crash with More Bees

### ISSUE THREAD

**Issue by Zygus42** [ForestryMC/Binnie#299]
forestry_1.12.1-5.5.0.178
forestry-binnie-mods-1.12.1-2.3.0.60
forestry-morebees-1.12.2-1.4.2
[crash-2017-08-30_13.42.39-client.txt](https://github.com/Lach01298/MoreBees/files/1262522/crash-2017-08-30_13.42.39-client.txt)

Also reported on More Bees.

**Comment by sebastianbhahn** [comment]
can confirm on 1.11.2
forestry-1.11.2-5.3.4.165
binnie-mods-1.11.2-2.1.0.41
morebees-1.11.2-1.4.1

[crash-2017-09-30_06.07.46-client.txt](https://github.com/ForestryMC/Binnie/files/1346383/crash-2017-09-30_06.07.46-client.txt)

**Comment by mezz** [comment]
This 1.12 bug may be fixed in the latest Binnie's version 2.5.0.90, can you try it and report back?

**Comment by temp1011** [comment]
Seems to be working for me in latest versions. Fixed?

[log of launching and world creation](https://github.com/ForestryMC/Binnie/files/1594779/latest.log)
