### ISSUE TITLE
[1.7.10] Some hardcodded localization

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#30]
In all project's code. Need to wrap to localize method.

**Comment by KorDum** [comment]
Hmm. Can I get localized strings from Forestry?
ex. `forestry.api.core.EnumTemperature.HELLISH.getName()` returns non-localized string.

**Comment by mezz** [comment]
Yes, you use this method:
`forestry.api.genetics.IClimateHelper#toDisplay(forestry.api.core.EnumTemperature)`

**Comment by KorDum** [comment]
How can I get IAllele object (or Allele GUID) from EnumAllele.* enums?
ex. 
``` JAVA
EnumAllele.Fertility fertility = EnumAllele.Fertility.NORMAL;
// I think it's not right
String guid = "forestry.fertility" + WordUtils.capitalize(fertility.toString().toLowerCase());
IAllele allele = alleleRegistry.getAllele(guid);
```

**Comment by KorDum** [comment]
> forestry.api.genetics.IClimateHelper#toDisplay(forestry.api.core.EnumTemperature)

And for EnumTolerance?

**Comment by KorDum** [comment]
`color` or `colour`?
ex. `getColor()`

**Comment by mezz** [comment]
Take a look at the handheld analyzer code in Forestry to see how the alleles are localized.

Forestry seems to mix `color` and `colour` all over the place. I don't have a preference.
