### ISSUE TITLE
[suggestion] change naming convention of jar

### ISSUE THREAD

**Issue by Zygus42** [ForestryMC/Binnie#300]
It would help mod pack developers a lot to have your mod with the "forestry-" prefix so that all forestry related mods sorted together in the mods folder.  ie:
        forestry-binnie-mods-1.12.1-2.3.0.60.jar
instead of
        binnie-mods-1.12.1-2.3.0.60.jar

**Comment by mezz** [comment]
Sorry but I don't really see the benefit of doing this. They are separate mods.
