### ISSUE TITLE
[1.12.1] Loaded a new chunk during chunk population in The Deep Dark

### ISSUE THREAD

**Issue by RealGrep** [ForestryMC/Binnie#301]
Don't know if this is caused by Extra Utilities 2 or this mod, but I can follow instructions, and the message said to file an issue. :)

Related XU2 issue: https://github.com/rwtema/extrautilities/issues/1677

As soon as I go to the Deep Dark, I start getting these messages:

`[Server thread/WARN] [FML]: Binnie Core loaded a new chunk (1, 16  Dimension: -11325) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.` This ceases as soon as I exit back to the Overworld.

That along with several "Can't keep up!" messages. The block lag is crippling, and it takes well over a minute to manage to actually exit the Deep Dark. During that whole time, lots of "Can't keep up!" messages appear with things like "Running 30886ms behind".

Let me know if I can do anything to help.

This is with binnie-mods-1.12.1-2.3.0.60.jar and extrautils2-1.12-1.6.jar, Minecraft 1.12.1, and forge-14.22.0.2467.

**Comment by frank89722** [comment]
I hava a similar issue here. But it's happening in overworld for me

This can make a noticeable lag spike every 15 seconds

`[11:54:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2124ms behind, skipping 42 tick(s)`
`[11:55:01] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2371ms behind, skipping 47 tick(s)`
`[11:55:03] [Server thread/WARN] [FML]: Binnie Core loaded a new chunk (-28, 15  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`

**Comment by SDUBZ** [comment]
this also still happens in 1.12.2 too thought forges vanilla gen fix would help but it didnt

**Comment by temp1011** [comment]
I'm guessing it's hives spawning in the deep dark so https://github.com/ForestryMC/Binnie/pull/486 could help if I can polish it.
