### ISSUE TITLE
[1.11] Mystical bee does not recognize botania flower

### ISSUE THREAD

**Issue by HammerDave** [ForestryMC/Binnie#306]
Running in 1.11 with extra bees and botania both installed, the mystical bee is not recognizing botania flowers.

This code chunk seems to be responsible for finding what blocks are valid flowers.  Not sure why it's failing to recognize it.  Maybe it's dependent on initialization order?

public static Block getBotaniaBlock(String name) {
		ResourceLocation key = new ResourceLocation("botania", name);
		return ForgeRegistries.BLOCKS.containsKey(key) ? ForgeRegistries.BLOCKS.getValue(key) : null;

**Comment by lvaleria** [comment]
Happens to me too on Direwolf 1.12 version 1.8.0 that uses Binnie's mods 1.12.2-.5.0.112, so when I breed a noble with a monastic and I get a Mystical queen, I have no way to let her die into a princess and drone for changing the flower with genetics. (workaround, find them in the wild and modify them before making a queen)
I tried botania mystic flowers and tall flowers of several colors.
thanks

**Comment by NealHicks** [comment]
ok it took me a bit of fumbling around and 3 edits but...There are 2 Mystical Bees (at least in ATM3 modpack.)

The MagicBees Mystical Bee is the one with Flower: Flowers trait and is found in the wild in Curious hives.  Its primary use seems to be breeding with Cultivated to get Eldritch, or with Mutable to get Invisible.  It makes a Mundane Comb.

The Mystical Bee from Binnie's Extra Bees is the one that has Flower: Mystical trait,  It is breeding product of Noble + Monastic bees.  It does not appear to be bred with anything else to make further bees.  It makes a Dripping Comb.
