### ISSUE TITLE
[1.12.1] Removing the Compartment Recipes with CraftTweaker does not work

### ISSUE THREAD

**Issue by MainFreak** [ForestryMC/Binnie#308]
According to the MineTweaker Log it should have been disabled, but it still shows up in JEI and is craftable, adding new recipes seems to work too, but I just can't get rid of the standard one despite the log saying that it has been removed.
I temporarily disabled the "new recipes" part of the script to check if re-adding a recipe somehow borked it (result: Even without new recipes the old ones are still present. I also tried disabling them with "more precise" Meta but the result did not change either). 
I am not sure if this is an issue with BinnieCore or something else, but I noticed this a few versions ago and hoped that it would have been fixed until now. This issue is really minor I think, but I would appreciate a fix or someone telling me if I did something wrong, since i really want to make those compartments a bit more expensive in my pack.

-**Script**: https://gist.github.com/MainFreak/8fbadd8ffae2067a47937fd7a92b4c1f

-**CT Log**: https://gist.github.com/MainFreak/d1102b7f5744d88c7604eda1ffd7012a

**Most Recent Tested Versions:**
>**binnie-mods-1.12.1-2.3.0.60**
>**CraftTweaker2-1.12-4.0.6**
>**forge-14.22.1.2478**

**Comment by MainFreak** [comment]
May I bump this issue? It is still relevant. 
(even on 1.12.2)

**Comment by Nedelosk** [comment]
I can't reproduce this in the newest version of binnies mods 1.12.

**Comment by StoneLegion** [comment]
Hello @MainFreak did you ever figure it out? I'm also having this issue I had made a post about it here #576 But I noticed yours today sadly being closed.

**Comment by MainFreak** [comment]
Unfortunately I never did. Not being able to properly balance storage systems, partially because of this issue, made me drop the project that this was intended for. 

No idea if it's fixed by now or not, but at the time of the post being closed it still didn't work for me in-game but seeing it being closed despite of that I just gave up.

**Comment by StoneLegion** [comment]
Thanks for the update. Yeah does not seem fixed here I even tried removing the recipe ID without luck. Not sure how it worked fine for @Nedelosk I guess he was lucky :)
