### ISSUE TITLE
Doesn't work on 1.12.2

### ISSUE THREAD

**Issue by TheLimePixel** [ForestryMC/Binnie#310]
Binnie's Mods seems to be one of the mods in my pack that don't work on MC 1.12.2
![image](https://user-images.githubusercontent.com/25333164/30587803-c14ee6b2-9d34-11e7-8784-025b13d9e742.png)

**Comment by Kris1432** [comment]
@EmosewaGamer can I trust you to go around all the mods github's haha

**Comment by TheLimePixel** [comment]
I've got you covered. :P

**Comment by mezz** [comment]
Thanks, fixed.
