### ISSUE TITLE
[1.12.1/SpongeForge - Botany] Any pollination/breeding method doesn't work

### ISSUE THREAD

**Issue by davv1** [ForestryMC/Binnie#312]
Forge: forge-1.12.1-14.22.1.2485-universal
SpongeForge: spongeforge-1.12.1-2444-7.0.0-BETA-2623
Forestry: forestry_1.12.2-5.5.6.197
Binnie: binnie-mods-1.12.1-2.3.0.60
OS: Windows 7 64bit

Can anyone help me if it's bug, or I'm just doing something wrong?
For few real days I was trying to figure out how to cross-breed my flowers. Or to just breed them. Anything. It just doesn't work for me. There are no new flowers in my garden, only randomly spawned just like in normal Forestry, on the grass of course.
I've got bees and butterflies there. And just nothing works.

When I was using Binnie back in 1.7.10, I had many, really many flowers of different colours and even had chance to see cross-breeded flower few times. What changed from this time so it's not working anymore?

Here's screenshot:

![2017-09-22_22 29 49](https://user-images.githubusercontent.com/13569795/30763282-c7a3f346-9fe5-11e7-8398-7a9fbdc13864.png)

**Comment by davv1** [comment]
In addition, any other breeding(tree, bee etc.) works flawlessy, I am able to get ExtraTrees' trees and more.

**Comment by davv1** [comment]
Any ideas or info what to do? Please.

**Comment by davv1** [comment]
Bump.

**Comment by Nedelosk** [comment]
@davv1 Have you looked at the flowers with the "debug view" (F3) and are you sure that the flowers are botany flowers and not only minecraft default flowers?

**Comment by davv1** [comment]
IIRC it's fixed in binnie-mods-1.12.2-2.5.0.167.jar - that's last version I played on multiplayer. I could normally do breeding of Botany Flowers and get many new species. Anyway, thanks for your interest.
