### ISSUE TITLE
[Botany] ArrayIndexOutOfBounds caused by ItemWeed

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ForestryMC/Binnie#314]
See https://github.com/Shadows-of-Fire/Plants/issues/23
Oredict registration using wildcard meta causes `ItemWeed` to not properly handle `getItemStackDisplayName` and instead crash.

**Comment by Peri-42** [comment]
I did some more testing, and got the same crash on a version with only Plants, Binnies (and Forestry of course), and TinyProgressions. Binnies and Plants played nice together, but TinyProgressions threw everything into chaos.
Here's the crashlog for that: https://pastebin.com/5NyXw9kV

**Comment by Shadows-of-Fire** [comment]
``` 
 @SubscribeEvent
  public void registerOre(OreDictionary.OreRegisterEvent event)
  {
    logger.debug(event.getOre().getDisplayName());
  }
```
This is what tiny progressions is doing, but this is crashing when I register that item to the oredict with wildcard meta.

**Comment by mezz** [comment]
Thanks for the report!
I have reported this to TinyProgressions on their Twitch channel (they want bug reports to go there for some reason).
