### ISSUE TITLE
[1.11.2] wrong hive labels (in TOP, a waila fork) and bee drops

### ISSUE THREAD

**Issue by sebastianbhahn** [ForestryMC/Binnie#318]
I found what I thought was a rocky hive in a cave; it's a water hive according to top (waila), and it dropped a valiant princess and drone. Still playing while typing this, I just found another "water hive" in the same cave; accidentally destroyed it (creative mode), not sure what it would have dropped. I just spent around 20 minutes exploring caves and crevices but I could find any more. I've also yet to find any actual rocky bees or hives.

I did a bit more testing in creative and all of binnie's mods hives are labelled as water hives in top, and all of them drop only valiant bees when destroyed with a forestry scoop. The hives are labelled correctly in just enough items.

forestry_1.11.2-5.3.4.165
binnie-mods-1.11.2-2.1.0.41
theoneprobe-1.1x-1.4.18
jei_1.11.2-4.5.1.296

**Comment by RusTit** [comment]
@mezz  I think this is already fixed (according to my test with theoneprobe-1.12-1.4.21.jar)
