### ISSUE TITLE
[1.7.10] Florist's Encyclopaedia does nothing at all

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#32]
This is replaced by Field Kit.
Need to removed this item from mod?

**Comment by mezz** [comment]
I think you should remove anything unused in 1.7.10. Players are already used to it not working, it should just be removed.

We can look at fixing or re-implementing things like this in the 1.11.2 branch.

**Comment by KorDum** [comment]
I do not think it needs to be repaired.
Because [here](https://binnie.mods.wiki/wiki/Florist%27s_Encyclopaedia) says:

> NOTE: Since version pre12 this item does nothing, and it's functionality has been replaced by the Field Kit.

I think the items were not removed for compatibility on servers without Forge backup after missing items.
