### ISSUE TITLE
[Extra Trees 1.12.2] - Idea - Option to control which forestry trees spawn naturally?

### ISSUE THREAD

**Issue by Spearkiller** [ForestryMC/Binnie#323]
After upgrading my modpack to 1.12.2 after remembering that this mod had been updated, I explored a new world and found trees such as Maple, Silver Lime, Raspberry and Blackberry, Wild Cherry, and a few others spawning naturally around the world.
Is there an option to disable this, and if not, is there any way we could get one? I was unable to find an option in the config.

As a bonus, regardless of whether the previous function exists or not, could there also be an option to blacklist/whitelist certain trees spawning in certain biomes? (Eg. enabling Sipiri to spawn naturally, but only in jungles, or Wild Cherry being able to spawn naturally in savannah's?)

**Comment by Nedelosk** [comment]
You can disable it in the forestry common config. "world.generate.trees"

**Comment by Spearkiller** [comment]
oh, ok, I guess I'm just blind then.

Still, The suggestion still stands for being able to control what ones can spawn, I guess?

**Comment by Nedelosk** [comment]
Added an option to control which trees spawn naturally to forestry.
