### ISSUE TITLE
High CPU time from forestry.apiculture.tiles.TileHive

### ISSUE THREAD

**Issue by OrdinatorStouff** [ForestryMC/Binnie#326]
As discussed with @mezz and in the AllTheCreators discord channel, worldgen hives appear to be taking an exorbitant quantity of CPU time. The server is almost never at 20 TPS anymore with zero obvious causes such as bad builds or overflowing mob farm. A visualVM profile (attached) shows that for Server Thread, approx 20% of CPU time is spent within TileHive.

SAMPLER (mod) counts list ~17,000 hive TEs as well, likely all loaded if I understand how sampler counts works.

The server is 1.12.2 and has Forestry, ExtraBees and Plants (relevant since according to Plants dev Shadows -- the iterator in the predicate looping through the flower states goes from ~8 states to ~100 states)

Many users report complaints with Rocky hives always damaging them when mining. Possibly this anecdotal evidence could support a theory that a higher-than-expected quantity of Rocky hives are spawning to account for the unusually high ~17,000 hive count when only ~4 players are online.
[snapshot-1508348415904.zip](https://github.com/ForestryMC/Binnie/files/1397051/snapshot-1508348415904.zip)

**Comment by mezz** [comment]
Thanks for the report!
Using the [TellMe mod](https://minecraft.curseforge.com/projects/tellme), I found that there are about 50x more rock hives than any other hive per chunk.
Also their bees don't seem to be able to find flowers, probably due to a bug.
