### ISSUE TITLE
[1.7.10] Backward Compatibility?

### ISSUE THREAD

**Issue by Enverex** [ForestryMC/Binnie#329]
I've just upgraded from 2.0-pre14 to 2.0.22.7 and FML has given me the warning:

```
ExtraBees:honeyCrystalEmpty
ExtraBees:honeyCrystal
Forestry:fluid.milk
Forestry:fluid.milk
Botany:encylopediaIron
Botany:encylopedia
ExtraTrees:drink
```

Is the newer version of the mod not strictly compatible with the older version in terms of upgrading?

**Comment by Enverex** [comment]
It's just occurred to me that the issue may be that I've gone from:

Forestry + Binnie's Mods + Binnie Patcher
to
Forestry + Newer Binnie Mods

Is that the most likely cause?

**Comment by Nedelosk** [comment]
We have removed some items. They all had not really any use.
