### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by Diamondman121314** [ForestryMC/Binnie#332]
Just got this error after the Forestry update earlier. Not sure if this is already known, but it doesn't hurt to report it. :D

https://pastebin.com/2CpUUqTr

**Comment by MainFreak** [comment]
I can confirm this

**Comment by Nedelosk** [comment]
Fixed in the [newest version](http://jenkins.ic2.player.to/job/Binnie's%201.12/).
