### ISSUE TITLE
[1.12.2] Crash: NoClassDefFoundError: forestry/core/PluginCore (game wont start)

### ISSUE THREAD

**Issue by ghost** [ForestryMC/Binnie#333]
[crash-2017-11-04_20.27.03-client.txt](https://github.com/ForestryMC/Binnie/files/1443435/crash-2017-11-04_20.27.03-client.txt)
sorry if i'm stupid about something

**Comment by Tencao** [comment]
Would also like to confirm this bug

**Comment by Nedelosk** [comment]
This bug is not caused by binnie it is caused by More Bees.
