### ISSUE TITLE
[1.12.2] Lab Stand doesn't work

### ISSUE THREAD

**Issue by Syncaidius** [ForestryMC/Binnie#335]
I've tried placing the handheld database and analyzer items on the lab stand, but it doesn't seem to accept any of them.

Apologies if this is now intended.  I've not used Binnie's mods since 1.7.10.

**Comment by mezz** [comment]
Thanks for the report!
Fixed in the latest version.
The lab stand should now work with all of those items.
Also, it will let you display any other item you want on top of it.
