### ISSUE TITLE
[1.12.2] Crash when open ItemDatabaseBotany

### ISSUE THREAD

**Issue by kellixon** [ForestryMC/Binnie#339]
[1.12.2]Forge 14.23.0.2538
[1.12.2]Binnie 2.5.0.90
The list of mods in the log
https://pastebin.com/WDucQAfp

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I am not able to replicate this issue, the Botanist Database works fine for me on client and server.
Please try to narrow down the issue by removing mods that may interfere. I am running with just Binnie's, Forestry, IC2, and Thermal Expansion.

**Comment by Nedelosk** [comment]
I am closing this because of no response.
