### ISSUE TITLE
[1.12.2]Fails to Inoculate Effect

### ISSUE THREAD

**Issue by SarahGreyWolf** [ForestryMC/Binnie#340]
Binnie's: V. 2.5.0.89
Forestry: V. 5.7.0.212
Attempting to innoculate or splice a bee with any effect does nothing.
It just continuously run with no change to the larvae.

**Comment by mezz** [comment]
Thanks for the report!
I tested and was able to turn a Barren larvae into an Abnormal larvae species, using the Inoculator.
Do you have a specific example of something that is not working, and can you include a screenshot?

**Comment by SarahGreyWolf** [comment]
I am referring to effect serums, such as poison and explorer

**Comment by mezz** [comment]
Ok thanks, I was able to reproduce the bug. Fixed in the next version.
