### ISSUE TITLE
[1.12.2] Analyst turns Pollen to Sapling

### ISSUE THREAD

**Issue by SarahGreyWolf** [ForestryMC/Binnie#341]
Binnie's: V. 2.5.0.89
Forestry: V. 5.7.0.212

Placing unanalysed pollen in an Analyst with DNA Dye turns the pollen into the analysed sapling for that pollen.

**Comment by mezz** [comment]
Thanks for the report!
Confirmed, I should be able to solve this soon.

**Comment by mezz** [comment]
Fixed in the next version of Binnie's.
