### ISSUE TITLE
[1.12.2] Compatibility w/ The One Probe and TOP Addons

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/Binnie#343]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.2542
- Forestry 1.12.2-5.7.0.212
- Binnie's Mods 1.12.2-5.0.96
- The One Probe 1.12-1.4.19
- TOP Addons 1.12.2-1.1.3

#### Issue Description

Hi there, 

This issue report also doubles as a feature request. 

The request would be to have native The One Probe support for Binnie's Mods. Regardless, I'll proceed with the issue.

The One Probe tooltip shows a silly number of tanks for the Brewery despite only actually having two. Which is weird. It seems the problem lies more specifically with TOP Addons who I've also reported this issue too.

However, should Binnie's Mods add native support for The One Probe (Given that it's the "standard" for block HUDs it would allow for the support to be native and therefore not have to rely on other mods for it where issues as such could occur.

I hope that you consider my request. Thanks for continuing to maintain such a fabulous mod. 

#### Issue Media

With TOP Addons
![Issue Media #1](https://ss.blamesnow.co.uk/2017/11/1510686020-1606de7d.png)

Without TOP Addons
![Issue Media #2](https://ss.blamesnow.co.uk/2017/11/1510686126-4ab40d63.png)

**Comment by DrManganese** [comment]
TOPAddons uses `IFluidHandler#getTankProperties()` from the capibility on facing `null` to get all the internal tanks. It seems like the capability is returning each tank six times.

**Comment by mezz** [comment]
Thanks for the report!
I'm not really interested in adding direct support for this type of mod, I think it's good enough when I can see the block's name.
I will fix these bugs so that TOPAddons works though, it sounds like the brewery is generally pretty broken.

**Comment by SnowShock35** [comment]
@mezz Thank you mezz. I can understand that you don't wish to add native support at this time. And I believe once I update tanks and RF capacity should work correctly not requiring really any other necessary support. 👍
