### ISSUE TITLE
[1.12.2] Shift-clicking into the Brewery GUI causes item loss

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/Binnie#345]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.2542
- Forestry 1.12.2-5.7.0.212
- Binnie's Mods 1.12.2-5.0.96
- The One Probe 1.12-1.4.19

#### Issue Description

When shift-clicking ingredients into the Brewery from Binnie's Mods the items that go into the respective slots become stuck there and are then lost when you try to remove them. I imagine that these slots are meant as ghost slots to set the recipe and that the row of slots down the bottom is for actual ingredients.

To circumvent this. Have it where the ingredient is added to the respective ghost slot (max size of one - and doesn't use an item) then the rest go into the actual inventory.  

#### Issue Media

https://ss.blamesnow.co.uk/2017/11/1510687246-d568ea05.gif

**Comment by mezz** [comment]
Thanks for the report!
I am resolving this by preventing shift-clicking into the recipe slots entirely.
They behave like ghost slots and should be specified manually, not with shift-click.
