### ISSUE TITLE
[1.12.2] Brewery just doesn't work

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/Binnie#346]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.2542
- Forestry 1.12.2-5.7.0.212
- Binnie's Mods 1.12.2-5.0.96
- The One Probe 1.12-1.4.19

#### Issue Description

I give the brewery everything it needs and it doesn't work. Please see previous issues before this one. 

#### Issue Media

https://ss.blamesnow.co.uk/2017/11/1510687643-240e69e4.gif

**Comment by SnowShock35** [comment]
Fixed - I don't recall seeing it in the changelog?

**Comment by mezz** [comment]
I am not sure what the problem you saw was. I did not do anything to fix it.

**Comment by SnowShock35** [comment]
Closing, refer to #347 for details.
