### ISSUE TITLE
[1.12.2] Brewery Weirdness: The next chapter

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/Binnie#347]
#### Issue Specifications

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2531
- Forestry 5.7.0.212
- Binnie's 2.5.0.97

#### Issue Description

1. ~~Localisation missing for Brewery error messages~~
2. Brewery error messages (specifically the no room in tank highlights the wrong slot
3. Right clicking a bucket on the block will not play the bucket sound and will attempt to open the GUI instead (which shows no fluids) but tooltips and closing then re-opening the GUI fixes it - desync?
4. No progress bar - it just kinda does it's thing and you can't really tell if it works - not very intuitive. EDIT: Okay so there is one but you have to hold tab to see it? In addition to my point about percentages and x out of x/x perhaps make it only show percentages until tab is pressed?  
5. Lack of redstone control or indication of whether redstone has an effect on the machines
6. Continuous use of power (What is this Minecraft 1.2.5?) 
7. Power bar fills from top to bottom - power is now a gas! 😛.
8. Both percentage and x out of x/x displayed on power tooltip. Not sure both are really necessary - just a personal opinion though
9. The machine status only tells you one problem at a time - why not list all problems e.g. insufficient power, insufficient input liquid, no items, output is full, etc.
10. ~~Missing help tooltip on grain slot on what is a valid input~~

#### Issue Media 

1. Localisation missing for Brewery error messages
2. Brewery error messages (specifically the no room in tank highlights the wrong slot
![](https://ss.blamesnow.co.uk/2017/11/1510908578-c5a07995.png)

7. Power bar fills from top to bottom - power is now a gas! 😛.
8. Both percentage and x out of x/x displayed on power tooltip. Not sure both are really necessary - just a personal opinion though
![](https://ss.blamesnow.co.uk/2017/11/1510908946-abd800bf.png)

9. The machine status only tells you one problem at a time - why not list all problems e.g. insufficient power, insufficient input liquid, no items, output is full, etc.
![](https://ss.blamesnow.co.uk/2017/11/1510909606-1e833ab2.png)

10. Missing help tooltip on grain slot on what is a valid input
![](https://ss.blamesnow.co.uk/2017/11/1510909270-6be3a887.png)

**Comment by mezz** [comment]
Thanks for the report!
I have fixed some of these issues and improved tooltips in general on machines.
I only saw this issue after, can you take another look with the latest version to see what is still an issue?

**Comment by SnowShock35** [comment]
@mezz  Fixed are crossed out and persistent issues are listed as well as new issues further down.

1. ~~Localisation missing for Brewery error messages~~
2. Brewery error messages (specifically the no room in tank highlights the wrong slot
3. Right clicking a bucket on the block will not play the bucket sound and will attempt to open the GUI instead (which shows no fluids) but tooltips and closing then re-opening the GUI fixes it - desync?
4. No progress bar - it just kinda does it's thing and you can't really tell if it works - not very intuitive. EDIT: Okay so there is one but you have to hold tab to see it? In addition to my point about percentages and x out of x/x perhaps make it only show percentages until tab is pressed?  
5. Lack of redstone control or indication of whether redstone has an effect on the machines
6. Continuous use of power (What is this Minecraft 1.2.5?) 
7. Power bar fills from top to bottom - power is now a gas! 😛.
8. Both percentage and x out of x/x displayed on power tooltip. Not sure both are really necessary - just a personal opinion though
9. The machine status only tells you one problem at a time - why not list all problems e.g. insufficient power, insufficient input liquid, no items, output is full, etc.
10. ~~Missing help tooltip on grain slot on what is a valid input~~

#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2549
- Forestry 5.7.0.212
- Binnie's Mods 2.5.0.101

#### Issue Description

1. No power or fluid capacity whatsoever now (even though you can still right click buckets and they appear in TOP too
2. No error messages show
3. Weird symbol in power tooltip on shift
4. No user button anymore

#### Issue Media

3. Weird symbol in power tooltip on shift
![](https://ss.blamesnow.co.uk/2017/11/2017-11-20_17.26.38.png)

**Comment by khodina88** [comment]
Any fix for the above-listed issue for the brewery (no capacity, no error messages, not producing anything)?

Minecraft 1.12.2
Micecraft Forge 14.23.1.2556
Forestry 5.7.0.213
Binnie's Extra Trees 2.5.0.102

Thanks!

**Comment by mezz** [comment]
I have not had time to work on a fix for these issues yet, sorry.

**Comment by mezz** [comment]
I have pushed a fix that resolves most of these issues.

Remaining issues with explanation:

> Right clicking a bucket on the block will not play the bucket sound and will attempt to open the GUI instead (which shows no fluids) but tooltips and closing then re-opening the GUI fixes it - desync?

The bucket will still make no sound, waiting on Forge PR: https://github.com/MinecraftForge/MinecraftForge/pull/4623
The desync with opening the gui is fixed though.

> Lack of redstone control or indication of whether redstone has an effect on the machines

> Continuous use of power (What is this Minecraft 1.2.5?)

> The machine status only tells you one problem at a time - why not list all problems e.g. insufficient power, insufficient input liquid, no items, output is full, etc.

Please open these as separate feature requests, they change how the mod works.

Thanks for the reports and let me know when you find more issues!

**Comment by SnowShock35** [comment]
Thanks @mezz I have opened two feature suggestions for the first two there, however I have since changed my mind on the machine status as this is still how it is in Forestry (to my knowledge) and seems only right that it stay similar to the mod that it is an addon for. 

Thanks for all your continued hard work on the mod. :heart: 🎄
