### ISSUE TITLE
[1.11.2] Honey Crystal does nothing at all

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#35]
Honey Crystal useless, because not implementing any logic.

**Comment by marcin212** [comment]
[this?](https://ftbwiki.org/Honey_Crystal) We could add it back.

**Comment by KorDum** [comment]
Yes. It is necessary to return.

**Comment by Nedelosk** [comment]
ef371173c951aca75a07fef9ee4621f96ca9283d
