### ISSUE TITLE
Chisel and bit and binnie mod

### ISSUE THREAD

**Issue by saphsara** [ForestryMC/Binnie#351]
Is there a way to allow blocks to work with chisel and bots?  Running server mc vet 1.12.2

**Comment by saphsara** [comment]
Oh I spoke with chisel and bit mod creator here is l8 k to what they said.

https://minecraft.curseforge.com/projects/xtones?gameCategorySlug=mc-mods&projectID=257573

**Comment by Nedelosk** [comment]
[Chisels-and-Bits Issue](https://github.com/AlgorithmX2/Chisels-and-Bits/issues/328)

**Comment by Nedelosk** [comment]
There is currently no way of adding this because there is no way of avoiding the TileEntiy.
