### ISSUE TITLE
genetics crash

### ISSUE THREAD

**Issue by seiverdamross** [ForestryMC/Binnie#352]
https://pastebin.com/Am2P2BKr

something is not returning a species root

https://github.com/ForestryMC/Binnie/blob/master-MC1.12/core/src/main/java/binnie/core/genetics/BreedingSystem.java#L427

**Comment by temp1011** [comment]
Do you have any modules from forestry disabled in your configs? Trying to work out if this is the same error as I am getting.

**Comment by temp1011** [comment]
Also fixed now like https://github.com/ForestryMC/Binnie/issues/331 or is this still a problem?
