### ISSUE TITLE
OreDict question

### ISSUE THREAD

**Issue by 016Nojr** [ForestryMC/Binnie#359]
The Scented and the Proven Gears are oredicted as "gearWood", but this causes problems with recipes looking for gearWood, also when AE2 is present in the same instance all recipes requiring wood gears will look for Proven or Scented gears.

Can the oredict entry be changed to something else than gearWood as it doesnt make sense (not for me atleast) since it's not just a regular hand-crafted gear.

**Comment by mezz** [comment]
Thanks for the report!
I agree that these should not be registered as "gearWood".
