### ISSUE TITLE
brewery not working at all

### ISSUE THREAD

**Issue by redgoblin88** [ForestryMC/Binnie#363]
me and my friend are wanting to make a full blown brewery with every drink but before we have the drinks we need something to make them with, so we got the brewery, noticed that it needed hops, grains and yeast but when we try to fill it with water the tank simply does not work (either that or it voids it) plus whilst testing with it in a creative world i noticed the power bar does not work and anything automatically inserted will get voided

here is a screenshot of what i have tried (draconic flood gate, immersive pipes, thermal fluiducts, ic2 fluid distributor and refined storage export bus with water)
![2017-12-02_18 16 25](https://user-images.githubusercontent.com/13396472/33518451-0bf349fa-d78d-11e7-8102-50782379b1f6.png)

so sumarised there are three main issues that i have found:

1. water cannot be inserted no matter what you try with whatever things from whatever mod 
2. inside the brewery, the RF bar does not update when supplied with power as it remains "empty"
3. automatically inserting items (grains, hops and anything that shouldn't be in) just get voided.

but what use is a bug report with no info of what i'm using which could conflict or prevent somebody trying to replicate? so here you go!

forge: 14.23.1.2556
Binnies: 1.12.2-2.5.0.103 (yes 104 and 105 are out but as far as the change logs are concerned there has been no brewery change)
forestry: 1.12.2-5.7.0.213

if you need any more information please ask, if you need a more "complete" or full modlist of what im using i can give you a link to the modpack

**Comment by Nedelosk** [comment]
Works fine for me.
![2018-11-09_22 12 11](https://user-images.githubusercontent.com/10259214/48288467-8bed8480-e46c-11e8-9107-7b83f3fcb5c4.png)
![2018-11-09_22 12 16](https://user-images.githubusercontent.com/10259214/48288468-8c861b00-e46c-11e8-91d6-5bdbd8d5fc85.png)
