### ISSUE TITLE
Suggestion: Acid and Poison - fluid registry name changes

### ISSUE THREAD

**Issue by Antillar** [ForestryMC/Binnie#364]
Currently the 2 liquids produced by the rarest branches of bees have absolutely no usage. They cannot even be placed in the world.

My suggestion is very simple:
* Change fluid registry name for Acid from **acid** to **sulfuricacid**. This allows this fluid to be used by many mods which work with chemistry, including Mekanism, GregTech and MineChem.
* Change fluid registry name for Poison from **poison** to **potion.poison**. This allows this fluid to be used everywhere normal poisonous potion is used. This makes other mods which work with liquids to somehow process this fluid for their own needs, and of course the potion of poison could be crafted from it then.

These changes are very small, but they will definitely have a strong positive effect on a gameplay in any large modpack containing this mod.

**Comment by Antillar** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/1312

**Comment by Nedelosk** [comment]
These two fluids were removed together with the liquid nitrogen.
