### ISSUE TITLE
Wooden Tiles

### ISSUE THREAD

**Issue by Xiaminou** [ForestryMC/Binnie#366]
![2017-12-07_20 32 27](https://user-images.githubusercontent.com/8670392/33739190-71e9b556-db9c-11e7-892b-af806205cb72.png)
![2017-12-07_20 32 30](https://user-images.githubusercontent.com/8670392/33739191-72058b78-db9c-11e7-927d-479ccab06b5d.png)

Minecraft: 1.12.2
Forge: 2556
Mods: [list.txt](https://github.com/ForestryMC/Binnie/files/1540629/list.txt)

**Comment by RusTit** [comment]
@mezz you can now close this.
