### ISSUE TITLE
[1.12.2]Several machines are not working

### ISSUE THREAD

**Issue by Attacker0922** [ForestryMC/Binnie#367]
I used Modern Skyblock 2 Pack. and binnie mod 1.12.2-2.5.0.102

Tile, Glass, Panel, Wood Workers and Genepool, Analysor, Lumbermill are not working. input with shift, with out shift. both not working. I think it's a ghost slot. I can't input anything in it(with shift, without shift.). I used hopper, look with the one probe and shift, item in a machine has been marked. item in a hopper also entered. but i can't use machine. i can't look not marked items in gui.
I put an item on the lap machine and breaking it, there will be two items.
(Sorry. I'm not good at English, so I used Google Translator.)

**Comment by Nedelosk** [comment]
Can't reproduce anything of this everything works fine.
