### ISSUE TITLE
Tileworker graphic error

### ISSUE THREAD

**Issue by Toapoint** [ForestryMC/Binnie#368]
https://imgur.com/a/xVNvV

Anyone else getting this???

**Comment by Trixz2018** [comment]
yes i can agree i am getting the same issue

**Comment by Lushtree** [comment]
My wife and I are getting this issue. Any solutions for it?

**Comment by Trixz2018** [comment]
just have to wait for a fix. We cannot do anything, only the forestry team can fix this

**Comment by twilytgardnfaery** [comment]
Attempting to use the tileworker anyway will create invisible blocks rather than the standard black/purple checked no texture appearance, and attempting to harvest said blocks causes a hard crash.

https://gist.github.com/twilytgardnfaery/08ae6e0b7c4b6ee77b6c2a73bb38647a
