### ISSUE TITLE
Binnie modeling stage crashing MC at launch

### ISSUE THREAD

**Issue by wugmump** [ForestryMC/Binnie#371]
Hope this info is sufficient. i see the forge/forestry/binnie's versions in the log fragment.

from the tail end of the FML log:

[07:32:42] [main/WARN]: Unable to resolve texture due to upward reference: #texture in binniecore:models/block/machine
[07:32:42] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b130.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-37.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (AdChimneys-1.12.1-3.2.1.0-build.0056.jar)
  DummyPlugin (ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 12/18/17 7:32 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.client.model.ModelStateComposition.apply(ModelStateComposition.java:43)
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:718)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.ModelStateComposition.apply(ModelStateComposition.java:43)
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:718)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.2
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 496434560 bytes (473 MB) / 2300559360 bytes (2193 MB) up to 10667687936 bytes (10173 MB)
	JVM Flags: 17 total; -Xmx10240m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2577 155 mods loaded, 155 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                          | Signature                                |
	|:----- |:------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                      | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                      | 8.0.99.99                | forge-1.12.2-14.23.1.2577.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                    | 14.23.1.2577             | forge-1.12.2-14.23.1.2577.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | advancedrocketrycore     | 1                        | minecraft.jar                                   | None                                     |
	| UCH   | ivtoolkit                | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCH   | opencomputers|core       | 1.7.1.43                 | minecraft.jar                                   | None                                     |
	| UCH   | actuallyadditions        | 1.12.2-r125              | ActuallyAdditions-1.12.2-r125.jar               | None                                     |
	| UCH   | redstoneflux             | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore                 | 4.3.7                    | CoFHCore-1.12.2-4.3.7.25-universal.jar          | None                                     |
	| UCH   | libvulpes                | 0.2.7.-21                | LibVulpes-1.12.2-0.2.7-21-universal.jar         | None                                     |
	| UCH   | advancedrocketry         | 1.2.6.-37                | AdvancedRocketry-1.12.2-1.2.6-37.jar            | None                                     |
	| UCH   | applecore                | 3.1.0                    | AppleCore-mc1.12.2-3.1.0.jar                    | None                                     |
	| UCH   | jei                      | 4.8.5.136                | jei_1.12.2-4.8.5.136.jar                        | None                                     |
	| UCH   | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCH   | aroma1997core            | 2.0.0.0.b130             | Aroma1997Core-1.12.2-2.0.0.0.b130.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aromabackup              | 2.1.1.3.b89              | AromaBackup-1.12.2-2.1.1.3.b89.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aromabackuprecovery      | 2.1.1.3.b89              | AromaBackup-1.12.2-2.1.1.3.b89.jar              | None                                     |
	| UCH   | astralsorcery            | 1.8.4                    | astralsorcery-1.12.2-1.8.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | cd4017be_lib             | 6.0.5                    | CD4017BE_lib-1.12.2-6.0.5.jar                   | None                                     |
	| UCH   | circuits                 | 6.0.3                    | AutomatedRedstone-1.12.2-6.0.3.jar              | None                                     |
	| UCH   | psi                      | r1.1-59                  | Psi-r1.1-59.jar                                 | None                                     |
	| UCH   | quark                    | r1.4-120                 | Quark-r1.4-120.jar                              | None                                     |
	| UCH   | autoreglib               | 1.3-15                   | AutoRegLib-1.3-15.jar                           | None                                     |
	| UCH   | baubles                  | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCH   | betteragriculture        | 1.2.1                    | betteragriculture-1.12.2-1.2.1.jar              | None                                     |
	| UCH   | betterbuilderswands      | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | betterthanbunnies        | 1.12.1-1.1.0             | BetterThanBunnies-1.12.1-1.1.0.jar              | None                                     |
	| UCH   | betterthanllamas         | 1.12.1-1.0.0             | BetterThanLlamas-1.12.1-1.0.0.jar               | None                                     |
	| UCH   | betterunderground        | 1.0.7                    | betterunderground-1.0.7.jar                     | None                                     |
	| UCH   | bibliocraft              | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | forestry                 | 5.7.0.217                | forestry_1.12.2-5.7.0.217.jar                   | None                                     |
	| UCH   | binniecore               | unspecified              | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| UCH   | binniedesign             | 1.0                      | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| UCH   | genetics                 | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| UCH   | botany                   | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| UCH   | extrabees                | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| UCH   | extratrees               | 2.5.0.106                | binnie-mods-1.12.2-2.5.0.106.jar                | None                                     |
	| UCH   | botania                  | r1.10-352                | Botania r1.10-352.jar                           | None                                     |
	| UCH   | codechickenlib           | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | brandonscore             | 2.3.4                    | BrandonsCore-1.12-2.3.4.134-universal.jar       | None                                     |
	| UCH   | buildcraftlib            | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcraftcore           | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcraftbuilders       | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcraftenergy         | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcraftfactory        | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcraftrobotics       | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcraftsilicon        | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | buildcrafttransport      | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCH   | sonarcore                | 5.0.3                    | sonarcore-1.12.2-5.0.3.jar                      | None                                     |
	| UCH   | calculator               | 5.0.2                    | calculator-1.12.2-5.0.2.jar                     | None                                     |
	| UCH   | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chickens                 | 6.0.2                    | chickens-6.0.2.jar                              | None                                     |
	| UCH   | ctm                      | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCH   | chisel                   | MC1.12-0.1.0.23          | Chisel-MC1.12-0.1.0.23.jar                      | None                                     |
	| UCH   | chiselsandbits           | 14.11                    | chiselsandbits-14.11.jar                        | None                                     |
	| UCH   | clayworldgen             | 1.1.0-1.12               | ClayWorldGen-1.1.0-1.12.0.jar                   | None                                     |
	| UCH   | cofhworld                | 1.0.2                    | CoFHWorld-1.12.2-1.0.2.10-universal.jar         | None                                     |
	| UCH   | comforts                 | 1.1.0                    | comforts-1.12.2-1.1.0.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | cyclopscore              | 0.10.24                  | CyclopsCore-1.12.2-0.10.24.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | commoncapabilities       | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
	| UCH   | computercraft            | 1.80pr1                  | ComputerCraft1.80pr1.jar                        | None                                     |
	| UCH   | controlling              | 3.0.5                    | Controlling-3.0.5.jar                           | None                                     |
	| UCH   | cookingforblockheads     | 6.3.17                   | CookingForBlockheads_1.12.1-6.3.17.jar          | None                                     |
	| UCH   | coralreef                | 2.0                      | CoralReef-2.2-1.12.2.jar                        | None                                     |
	| UCH   | cucumber                 | 1.0.3                    | cucumber-1.12-1.0.3.jar                         | None                                     |
	| UCH   | custommainmenu           | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar               | None                                     |
	| UCH   | eleccore                 | 1.8.434                  | ElecCore-1.12.2-1.8.434.jar                     | None                                     |
	| UCH   | deepresonance            | 1.5.0                    | deepresonance-1.12-1.5.0.jar                    | None                                     |
	| UCH   | dldungeonsjdg            | 1.10.2                   | DoomlikeDungeons-1.10.2-MC1.12.2.jar            | None                                     |
	| UCH   | thermalfoundation        | 2.3.7                    | ThermalFoundation-1.12.2-2.3.7.18-universal.jar | None                                     |
	| UCH   | draconicevolution        | 2.3.5                    | Draconic-Evolution-1.12-2.3.5.269-universal.jar | None                                     |
	| UCH   | harvestcraft             | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
	| UCH   | duckcraft                | 3.0.7                    | Duckcraft-1.12.2-3.0.7.jar                      | None                                     |
	| UCH   | elevatorid               | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                    | None                                     |
	| UCH   | endores                  | 1.12.2-r1                | End Ores-1.12.2-r1.jar                          | None                                     |
	| UCH   | enderstorage             | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | enderutilities           | 0.7.6                    | enderutilities-1.12.2-0.7.6.jar                 | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCH   | mantle                   | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct               | 1.12-2.8.1.49            | TConstruct-1.12-2.8.1.49.jar                    | None                                     |
	| UCH   | extrautils2              | 1.0                      | extrautils2-1.12-1.7.1.jar                      | None                                     |
	| UCH   | fairylights              | 2.1.1                    | fairylights-2.1.1-1.12.jar                      | None                                     |
	| UCH   | farmingforblockheads     | 3.1.5                    | FarmingForBlockheads_1.12-3.1.5.jar             | None                                     |
	| UCH   | fastleafdecay            | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | forgeendertech           | 1.12.1-4.3.0.0           | ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar    | None                                     |
	| UCH   | forgelin                 | 1.6.0                    | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | ichunutil                | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCH   | ftbl                     | 4.2.5                    | FTBLib-4.2.5.jar                                | None                                     |
	| UCH   | ftbu                     | 4.2.4                    | FTBUtilities-4.2.4.jar                          | None                                     |
	| UCH   | funkylocomotion          | 1.0                      | funky-locomotion-1.12.2-1.1.0.jar               | None                                     |
	| UCH   | gravestone               | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCH   | guideapi                 | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCH   | harvest                  | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                       | None                                     |
	| UCH   | hats                     | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCH   | hatstand                 | 7.0.0                    | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UCH   | ikwid                    | 1.0.2                    | ikwid-1.0.2.jar                                 | None                                     |
	| UCH   | theoneprobe              | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                     | None                                     |
	| UCH   | immersiveengineering     | 0.12-75                  | ImmersiveEngineering-0.12-75.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | indlog                   | 1.0.3                    | InductiveLogistics-1.12.2-1.0.3.jar             | None                                     |
	| UCH   | instantunify             | 1.0.7                    | instantunify-1.12.2-1.0.7.jar                   | None                                     |
	| UCH   | integrateddynamics       | 0.9.9                    | IntegratedDynamics-1.12.2-0.9.9.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | integrateddynamicscompat | 1.0.0                    | IntegratedDynamics-1.12.2-0.9.9.jar             | None                                     |
	| UCH   | integratedtunnels        | 1.3.6                    | IntegratedTunnels-1.12.2-1.3.6.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks            | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar                | None                                     |
	| UCH   | ironchest                | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCH   | jehc                     | 1.3.1                    | jehc-1.12-1.3.1.jar                             | None                                     |
	| UCH   | jeibees                  | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
	| UCH   | jeiintegration           | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar              | None                                     |
	| UCH   | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | jeresources              | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar         | None                                     |
	| UCH   | magicbees                | 1.0                      | MagicBees-1.12-3.1.7.jar                        | None                                     |
	| UCH   | modelloader              | 1.0.5                    | modelloader-1.0.5.jar                           | None                                     |
	| UCH   | magneticraft             | 2.0.5                    | Magneticraft_1.12-2.0.5.jar                     | None                                     |
	| UCH   | malisiscore              | 1.12.2-6.3.0             | malisiscore-1.12.2-6.3.0.jar                    | None                                     |
	| UCH   | malisisdoors             | 1.12.2-7.2.2             | malisisdoors-1.12.2-7.2.2.jar                   | None                                     |
	| UCH   | mob_grinding_utils       | 0.3.4                    | MobGrindingUtils-0.3.4.jar                      | None                                     |
	| UCH   | modnametooltip           | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                | None                                     |
	| UCH   | morechickens             | 3.0.0                    | morechickens-1.12.2-3.0.0.jar                   | None                                     |
	| UCH   | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | mysticalagriculture      | 1.6.6                    | mysticalagriculture-1.12-1.6.6.jar              | None                                     |
	| UCH   | netherendingores         | 1.12.2-1.1               | Netherending-Ores-1.12.2-1.1.jar                | None                                     |
	| UCH   | netherportalfix          | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
	| UCH   | notenoughwands           | 1.5.9                    | notenoughwands-1.12-1.5.9.jar                   | None                                     |
	| UCH   | opencomputers            | 1.7.1.43                 | OpenComputers-MC1.12.1-1.7.1.43.jar             | None                                     |
	| UCH   | partyparrots             | 1.0.0                    | PartyParrots-1.12.1-1.0.0.jar                   | None                                     |
	| UCH   | shetiphiancore           | 3.5.5                    | shetiphiancore-1.12.0-3.5.5.jar                 | None                                     |
	| UCH   | platforms                | 1.4.1                    | platforms-1.12.0-1.4.1.jar                      | None                                     |
	| UCH   | portalgun                | 7.0.0                    | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCH   | reborncore               | 3.5.3.174                | RebornCore-1.12.2-3.5.3.174-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | quantumstorage           | 4.4.6                    | QuantumStorage-1.12-4.4.6.jar                   | None                                     |
	| UCH   | randomthings             | 4.0.8                    | RandomThings-MC1.12.2-4.0.8.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | reauth                   | 3.5.2                    | ReAuth-3.5.2.jar                                | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCH   | reccomplex               | 1.4.6                    | RecurrentComplex-1.4.6.jar                      | None                                     |
	| UCH   | thermalexpansion         | 5.3.7                    | ThermalExpansion-1.12.2-5.3.7.31-universal.jar  | None                                     |
	| UCH   | redstonearsenal          | 2.3.7                    | RedstoneArsenal-1.12.2-2.3.7.18-universal.jar   | None                                     |
	| UCH   | xreliquary               | 1.12.2-1.3.4.728         | Reliquary-1.12.2-1.3.4.728.jar                  | None                                     |
	| UCH   | rftools                  | 7.15                     | rftools-1.12-7.15.jar                           | None                                     |
	| UCH   | rftoolscontrol           | 1.7.0                    | rftoolsctrl-1.12-1.7.0.jar                      | None                                     |
	| UCH   | rftoolsdim               | 5.05                     | rftoolsdim-1.12-5.05.jar                        | None                                     |
	| UCH   | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCH   | roots                    | 0.104                    | roots-2-0.104.jar                               | None                                     |
	| UCH   | spiceoflife              | 1.3.11                   | SpiceOfLife-mc1.12-1.3.11.jar                   | None                                     |
	| UCH   | stevescarts              | ${version}               | StevesCarts-1.12.2-2.4.12.62.jar                | None                                     |
	| UCH   | storagedrawers           | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCH   | sync                     | 7.0.0                    | Sync-1.12.2-7.0.1.jar                           | None                                     |
	| UCH   | tabula                   | 7.0.0                    | Tabula-1.12.2-7.0.0.jar                         | None                                     |
	| UCH   | thermalcultivation       | 0.1.2                    | ThermalCultivation-1.12.2-0.1.2.8-universal.jar | None                                     |
	| UCH   | thermaldynamics          | 2.3.7                    | ThermalDynamics-1.12.2-2.3.7.14-universal.jar   | None                                     |
	| UCH   | twilightforest           | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar     | None                                     |
	| UCH   | unifieditems             | 1.7.2.206                | UnifiedItems-1.12.2-1.7.2-206.jar               | None                                     |
	| UCH   | vc                       | 5.6.0                    | ViesCraft-1.12.2-5.6.0.jar                      | None                                     |
	| UCH   | waystones                | 4.0.17                   | Waystones_1.12.1-4.0.17.jar                     | None                                     |
	| UCH   | woot                     | 1.12.2-0.0.4             | woot-1.12.2-0.0.4.jar                           | None                                     |
	| UCH   | adchimneys               | 1.12.1-3.2.1.0           | AdChimneys-1.12.1-3.2.1.0-build.0056.jar        | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b130.jar)
  
ForgelinPlugin (Forgelin-1.6.0.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-37.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.jar)
  c4.comforts.asm.SleepTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  shetiphian.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (AdChimneys-1.12.1-3.2.1.0-build.0056.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockStateChange
DummyPlugin (ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.28.10 355.11.10.10.20.111' Renderer: 'NVIDIA GeForce GT 750M OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.5.3.174
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.23.1.2577
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.28.10 355.11.10.10.20.111, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
[07:32:42] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/josh/Documents/Curse/Minecraft/Instances/The Daddy Pack/crash-reports/crash-2017-12-18_07.32.42-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by temp1011** [comment]
Is this fixed by https://github.com/ForestryMC/Binnie/pull/418?
