### ISSUE TITLE
Unable to resolve texture

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/Binnie#373]
### Heyo ###
Was reading through the console and noticed this was being spammed. Thought you might want to know.
#### Versions ####
- Minecraft 1.12.2
- forestry_1.12.2-5.7.0.218
- binnie-mods-1.12.2-2.5.0.106
```
Unable to resolve texture due to upward reference: #texture in binniecore:models/block/machine
```
[Complete Log](https://gist.github.com/bookerthegeek/7bcce558a695d1784e0964914b0f14ab)
Let me know if you need anything else.

**Comment by RusTit** [comment]
@mezz You can close this issue.

**Comment by bookerthegeek** [comment]
I see its fixed. Thanks for the fix.
