### ISSUE TITLE
[1.12.2] [Question] Wooden Gear

### ISSUE THREAD

**Issue by Draskh** [ForestryMC/Binnie#374]
If binnies Mods are present in my mod pack the normal wooden gear of Applied Energistics is deactivated. I try now to figure out which mod that does. 
Does Binnie's Mods have a function that replaces wooden gears?

**Comment by mezz** [comment]
Looks like the Proven Gear is oredict "gearWood".
I will remove this oredict name, it's not really correct since the Proven Gears are a lot more expensive.

**Comment by mezz** [comment]
Duplicate of https://github.com/ForestryMC/Binnie/issues/359

**Comment by Draskh** [comment]
Everything works fine now, thanks!
