### ISSUE TITLE
[1.12.2]Wrong Translation Key

### ISSUE THREAD

**Issue by SihenZhang** [ForestryMC/Binnie#383]
![](https://i.imgur.com/ef5cwlU.png)
All kinds of Compartments[1], Lab Stand[2], Analyzer, Incubator, Genepool, Acclimatiser, Splicer, and some descriptions about Stimulator Usage[3] have no Localization.
![1](https://i.imgur.com/u7MA7jq.png)
![2](https://i.imgur.com/us8Msvw.png)
![3](https://i.imgur.com/Iq4dTXf.png)

**Comment by RusTit** [comment]
@mezz you may close this.
