### ISSUE TITLE
Model Programming Issues

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ForestryMC/Binnie#387]
https://gist.github.com/P3rf3ctXZer0/c771b84b2e636e3e8c7168ee907b4784

8 Models have a fair amount of errors. I don't care if you fix it I just won't use the mod XD Hope this helps you fix some issues.

**Comment by temp1011** [comment]
Pretty sure this is a typo fix - I'll try and do it now.
EDIT: I'm bad at code but this should be fixed - building now to check
EDIT2: I'm an idiot and didn't clone

**Comment by RusTit** [comment]
@mezz You can close this issue. (#418 #421 )
