### ISSUE TITLE
Proposal: change or remove the minimum 500 mB input liquid requirement

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/Binnie#392]
I was trying to use spare 500 mB water and some growth medium item to get the growth medium liquid. JEI shows that the recipe is "25 mB water + 1 growth medium item -> 25 mB growth medium liquid, with 20% item loss".

![2018-01-07_14 05 37](https://user-images.githubusercontent.com/9113033/34654667-d9823f42-f3b3-11e7-9851-8fbf46960df1.png)

However, I got this error notice after one working cycle:

![2018-01-07_14 03 00](https://user-images.githubusercontent.com/9113033/34654645-85739734-f3b3-11e7-9ac2-9d09d8f876b8.png)

By narrowing down to the codebase, I noticed this:
https://github.com/ForestryMC/Binnie/blob/5ec886ee133213b39891a04824ce2a917f1b1541/genetics/src/main/java/binnie/genetics/machine/incubator/IncubatorRecipe.java#L53

It looks like the `fluid.amount >= 500` precondition has been there since the beginning of the time. However, this can be extremely annoying when you run into situations where you have 25 mB extra:
![2018-01-07_14 07 39](https://user-images.githubusercontent.com/9113033/34654705-618c29f2-f3b4-11e7-9449-11f6bc15e02c.png)

Searching on the internet does not reveal anything about whether it is designed as it is or not. Considering that the only recipe that involves with growth medium liquid is the one of making bacteria liquid (which only costs 25 mB growth medium), I assume it is the initial design choice. However it doesn't change the fact that some random fluid of 25 mB is not easy to deal with. 
Pipette does working on taking the spare 25 mB growth medium out; on the other hand, it also means that I have to do it multiple times until I fully automate the incubator. 

My proposals are listed here:
1. change `fluid.amount >= 500` to `fluid.amount > 500`, so that it's a bit easier to deal with. Or,
2. remove the amount restriction, which is probably against the initial design.

**Comment by RusTit** [comment]
@mezz If everything is OK, you can close
