### ISSUE TITLE
[1.12.2] Cascading World Generation

### ISSUE THREAD

**Issue by Draskh** [ForestryMC/Binnie#393]
I traveled back from the Nether and got the following:

02:22:42] [Server thread/WARN] [FML]: Binnie Core loaded a new chunk (4, -31  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by walker-dev** [comment]
this is not an issue, basicly it says it did set a beehive/tree on -4 -31 in the nether.
you can disable logging in forge.cfg
`# Log cascading chunk generation issues during terrain population.
    B:logCascadingWorldGeneration=false`

**Comment by temp1011** [comment]
duplicate https://github.com/ForestryMC/Binnie/issues/315?
