### ISSUE TITLE
[1.7.10] Custom Modpack Crash

### ISSUE THREAD

**Issue by EcoSage** [ForestryMC/Binnie#396]
Hello,

I am receiving an error, which seems to be resulting from a duplicated class file. Not 100% sure, nor do I know how to fix it.

**Crash Report:**
_https://gist.github.com/SamosSage/0df1b92c95f9814bc3f37450657f9937_

Thank You,

Samos

**Comment by 3TUSK** [comment]
Remove Binnie Patcher; it is no longer needed for the updated version (i.e. 2.0.xx).

Duplicated of #181 and others.
