### ISSUE TITLE
Osange or Osage?

### ISSUE THREAD

**Issue by ElvenChaos** [ForestryMC/Binnie#399]
When I was doing ~~wikipedia~~ research into the various foods added by this mod, I noticed extratrees:food:38 being named "Osange Orange" instead of "Osage Orange" as ~~wikipedia~~ research would suggest otherwise. Which is correct?

**Comment by nhyty** [comment]
This seems to back Osage over Osange
http://www.botanic.cam.ac.uk/Botanic/Plant.aspx?p=27&ix=47&pid=0&prcid=0&ppid=0

**Comment by nhyty** [comment]
Also, am happy to fix if you want this changing 😄

**Comment by ElvenChaos** [comment]
I would think a fix would be appropriate :D

**Comment by temp1011** [comment]
I think this is a US vs GB difference. Localisation is in en_GB but not en_US https://github.com/ForestryMC/Binnie/blob/42435ea142bb28978625e461cd7b176af0d8979b/extratrees/src/main/resources/assets/extratrees/lang/en_GB.lang#L8.
