### ISSUE TITLE
River bee does not produce clay comb [v2.5.0.112]

### ISSUE THREAD

**Issue by TacoMage** [ForestryMC/Binnie#400]
River bees do not produce their secondary Clay Combs. The breed is still listed as having a 20% chance in JEI Bees and wiki as well as providing those combs through the escritoire.

Tested this under numerous circumstances in a world with only Forestry 5.7.0.236 and Binnie's 2.5.0.112 to exclude mod interactions being the culprit.

Tested with the bees in River biome, non-river biome, apiary, alveary, bee house, and each with and without a base made entirely of clay.  Also attempted using a variety of both forestry and extra bees frames.

**Comment by mezz** [comment]
To produce their specialty, the bees must be at their exact preferred temperature and humidity (ignoring tolerance).
Based on the code, there should be no other restrictions on the river bee.
Can you try  moving them to an area with the exact right temperature and humidity?

**Comment by TacoMage** [comment]
Yup, that was it, my bad.  I was thinking in terms of testing in things equivalent to the River Biome and not in terms of what the bee's actual qualities were.  The less rigorous part of my brain assumed the two would be the same.
