### ISSUE TITLE
Can't incubate larvae without restart

### ISSUE THREAD

**Issue by NesilR** [ForestryMC/Binnie#401]
Greetings!  

I'm currently playing on Direwolf20's 1.12.2 (v1.7.1) pack (using the latest build of Binnie's Mods, 2.5.0.112), and I seem to be experiencing a bug that is somewhat like https://github.com/ForestryMC/Binnie/issues/391 .  

I'm attempting to incubate a larvae with liquid growth medium, and it claims there is no valid recipe.  If I restart my server / game, it processes exactly one larvae, then goes back to claiming there is no valid recipe.  (See link below -- 5 PNGs that wouldn't attach)

I've not seen this bug mentioned anywhere else, so I have been reluctant to post, as I assumed others would have arrived at this point by now.  Any suggestions?

https://drive.google.com/open?id=1Np5coZxwP5j8FJJo-kLL-VGCWN8I1X4f

**Comment by mezz** [comment]
Thanks for the report!
There is an internal issue with Binnie's transfer utility that keeps some machines from working properly. The real fix is in progress but I haven't had much time to work on it recently.

**Comment by NesilR** [comment]
Understood; good luck!  And thank you for modding!  ^_^

**Comment by Xirema** [comment]
My workaround to this issue has been to add items to the incubator in two steps, which kick-starts the machine into working. This has then been hampered by the "No Space in Tank" bug, but that seems to have been fixed: https://github.com/ForestryMC/Binnie/pull/395

**Comment by NesilR** [comment]
Nice, thanks!

**Comment by NesilR** [comment]
So yeah, that works perfectly, awesome!  Putting larvae in the machine before the growth medium seems to kick it into working permanently.  Perhaps until a restart of the server?

**Comment by RusTit** [comment]
@mezz Checked on the current version, everything ok
