### ISSUE TITLE
Combined Ceramic Blocks seem to not render

### ISSUE THREAD

**Issue by asiekierka** [ForestryMC/Binnie#402]
Binnie's Mods 2.5.0.112, Forge .2599, tested with and without various combinations of other mods, in particular OptiFine and FoamFix are not involved.

![](https://img.asie.pl/hIV2)

**Comment by mezz** [comment]
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/Binnie/issues/368

**Comment by asiekierka** [comment]
Oh, sorry.
