### ISSUE TITLE
[1.12.2] Certain trees not giving fruit

### ISSUE THREAD

**Issue by CakeFlour** [ForestryMC/Binnie#404]
While playing in Multiplayer on this modpack I decided to get into forestry mods.
Everything works as expected, no problems with bees, saplings, etc.
However I noticed that certain trees that normally bare fruit do not. 
Standard example is the Orange, Pomello, Lemon, Etc. Trees. They grow as normal, but do not give any fruit even when it says the leaves are ripe. (This shown by WALIA, or whatever the equivalent is in this pack)
The texture of the leaves to show the ripeness does not change at all, despite saying ripe.
I've tried waiting for time to pass ingame naturally and using Bonemeal/Forestry Fertilizer on the leaves with no luck on either.
I'm not sure if this is in fact an issue with the Mod itself, a Modpack, or the server.
Some insight on this is appreciated, Thanks in advance.
(Currently running Direwolf20 1.12.2 (version 1.8.0) and the problem still remains)
This isn't consistent among trees, some trees will still give fruit, Ie. Hill Cherry.
ones that do not give fruit are said trees above, and Banana trees. (which grow like Cocoa pods, rather than in the leaves)

**Comment by Drazuam** [comment]
I am also having this problem.  After bonemealing an entire oak apple tree around three times, I got a single apple.  Some trees (in my case lime trees from binnie's) dont seem to drop at all.  Some kind of RNG may be screwed up?

Even when putting a "higher" yield trait on these saplings, a fruit drop is either not possible or extremely rare.

**Comment by TheHuntrod** [comment]
I am having the same problem in an All the Mods 3 pack. I am trying to use an orchard to farm fruits and nuts from trees. It works with the original forestry fruit but I could not get it working with coconut, which is the best for seed oil in this pack. I have it set up correctly and it works with the Hill Cherry.

**Comment by Enderknight2016** [comment]
I am having the Same issue in FTB Revelation with Wild Cherry, Redcurrent, and Raspberry. Texture won't update when ripe and the trees will not drop saplings without a grafter. No Fruit at all.

**Comment by caHocke** [comment]
Are there any updates to this bug?

**Comment by zackeezy** [comment]
Is this issue still being worked on?

**Comment by Keridos** [comment]
@mezz a fix for this would be much appreciated.

**Comment by Bulldogg6404** [comment]
This fix appears to have worked for the trees which have leaf block fruit yields, but some trees (namely the jungle fruit family: banana, red banana, papaya, and plantain) still do not generate fruit when they are grown from saplings. This might be intentional, as it maintains the behavior of cocoa beans from vanilla, but it would suggest an inability to obtain some fruits from whichever trees do not generate naturally with the world.

**Comment by krisjenner** [comment]
Can confirm above on binnie-mods-1.12.2-2.5.1.188 // forestry_1.12.2-5.8.2.387
