### ISSUE TITLE
[1.7.10] Ink Sacs & Clay

### ISSUE THREAD

**Issue by Klein1759** [ForestryMC/Binnie#408]
This is in regards to the latest binnie-mods-1.7.10-2.0.22.7.jar
Upon upgrading to this version I noticed that Ink Sacs and Clay could no longer be created from bees even though the analyzer said it could.

**Comment by KorDum** [comment]
Biome is River?

**Comment by Klein1759** [comment]
Using super bees. All that was bread out. Had no issue with this before this version. Was working fine. This latest update changed that. And so far it's only these 2.

**Comment by Klein1759** [comment]
Has this been fixed or was this just closed?

**Comment by Nedelosk** [comment]
We no longer make changes to the 1.7.10 version of binnies mods. So I closed this.

**Comment by Klein1759** [comment]
Apparently as this was originally from February and never was addressed.
