### ISSUE TITLE
Incubator doesnt work right

### ISSUE THREAD

**Issue by liny-fox** [ForestryMC/Binnie#411]
Incubators complain that there is no valid recipe if the starting fluid is piped in before the solid item is in the inventory.
Dumping in input liquid with a bucket works fine and fixes the problem if the input tank has room in it for more fluid.
This breaks automation of the machine because if the input item runs out you have to break the machine, fill it manually with a bucket of liquid, add the item in then you can continue piping in fluids (and im guessing items too at that point)

This is in the Direwolf20 1.12.2 modpack.

**Comment by liny-fox** [comment]
Looks to be related to #401

**Comment by mezz** [comment]
There have been some recent fixes and this might be fixed. 
Please try on the latest version, is this still an issue?
