### ISSUE TITLE
Texture glitch

### ISSUE THREAD

**Issue by RusTit** [ForestryMC/Binnie#414]
Hi, I found a bug with textures using JEI.

From the block of ceramics to the block of ectoplasm there are no textures, in addition, the logs are strange.
![2](https://user-images.githubusercontent.com/29846693/36412920-ebbab6b8-1667-11e8-9305-19f67fecaff9.png)
![1](https://user-images.githubusercontent.com/29846693/36412919-eb8d7f40-1667-11e8-9c2d-468048630039.png)

Minecraft 1.12.2
forge-1.12.2-14.23.2.2611-installer-win

SHA256 | Mod
------------ | -------------
f1f255e6d2aca566d72912a466bf0fcad4162925da2701924615ef894d62770c | *appliedenergistics2-rv5-stable-8.jar
7122b76e07b0439624f3bff329151793e042533d7c90f15a104633b917343eb6 | *BiblioCraft[v2.4.3][MC1.12.0].jar
fe0e4b558a3e2d66555a04bb26ba02082aef536aa832002661cd48fa19a50d12 | ***binnie-mods-1.12.2-2.5.0.112.jar**
207220929a697e4ec59f159cfb448668dbdcdc55b710dd8a6dca90e6d9f17a0b | *buildcraft-7.99.15.jar
a4bd9680e7d5574175057d20eef058bc3773666157c3de95467f86b35c09744d | *CodeChickenLib-1.12.2-3.1.5.331-universal.jar
3d064c899c8a05524c21c4a3159f4d63a31caa23f49055b4575dfc3c7342a1fe | *CoFHCore-1.12.2-4.3.10.5-universal.jar
c0213b112dba853d2786773d223bd02070059bf347650d4b650e84db3bcf4fde | *CoFHWorld-1.12.2-1.1.1.12-universal.jar
615be8a7d77594e26e07d4eedd0222c1019262925304d942004268caccd9025d | ***forestry_1.12.2-5.8.0.250.jar**
c9dca2fc1da5206f00f048bcc49c55b2836c2bb6816a7f5c1c7a11cef16c15fb | *industrialcraft-2-2.8.54-ex112.jar
16a39fb413b016d250221c87c717d6e7eac32be00603a5446985bce5e8ad1bd8 | *ironchest-1.12.2-7.0.39.823.jar
7c3d6d7ad179eb5939e166d6fad33eb5aecbefa463a1727e7c7aa7dd2f8c2f36 | *irontanks-2.1.0-beta.5.jar
a3fd090501765b802f13a34987aa01a258da64efe881a1e7d63b66f2b5d9b731 | *jei_1.12.2-4.8.5.157.jar
cab0e04b7b3e04942347ff10efdeb98184d1e48d158faffc7671cc567bb5e488 | *journeymap-1.12.2-5.5.2.jar
7f9d88d152f9767b8f5f8c91a20fd50c5ac417c884d88448d2e1c7ab3f49f0e7 | *Magical+Map-1.12.2-3.1.0.jar
0ab6ff24829eeb06d8e00d33548be9ab9bf0191e5ad5e181bbcd5fbec23f3baf | *OptiFine_1.12.2_HD_U_C9.jar
68a2b7e578d2ee92901784d1169b4dbae07e7217f8b0dc3024ed112ef165b97b | *Placebo-1.12.2-1.2.0.jar
885624d65e9f09678a766701866c661d73f1c736dc2795cbfc016bd3859bb267 | *RedstoneFlux-1.12-2.0.1.2-universal.jar
7f84e450364be75d7907aa20ac17586573c414eb360faea870cc20dc147da955 | *ThermalCultivation-1.12.2-0.1.5.3-universal.jar
593e6803e76fd0cd62c464b7ee7ce68bae8ab8e9a0f6176bc6719464500bee03 | *ThermalDynamics-1.12.2-2.3.10.4-universal.jar
58ecc439bd9dc097b982dd3623fc9105139f8d23986d7212d82f7887fb8b6f11 | *ThermalExpansion-1.12.2-5.3.10.15-universal.jar
8bf88102e92124470b47e5b133e8f6a81b93bc608787ec7e8e2db05c3c81c723 | *ThermalFoundation-1.12.2-2.3.10.6-universal.jar
e3b8399b7b4584f0aa90a3bd4b04fe88fb1a7eb367e37a555f57227c9614a6f0 | *UniDict-1.12.2-2.3.2b.jar
69a402bc5afbbccd4d58ef1160481aae8eeabd4b838efadafad651c5a3365137 | *WanionLib-1.12.2-1.4.jar

**Log:**
https://gist.github.com/RusTit/e72ad745ab315cf30b62e5ade2348bd7

**Comment by KorDum** [comment]
Please use [gist](gist.github.com) for logs.

**Comment by RusTit** [comment]
I fixed it myself, close it
