### ISSUE TITLE
Ghost Fence Recipes

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/Binnie#417]
## Heyo ###
So there I was, trying to CraftTweaker the fence recipes to make them unified and more expensive. When all of a sudden I see a recipe for them that should not be their. In this screenshot it is the Holly Fence. This is also with just Forestry and Binne mod installed

![screenshot](https://i.imgur.com/A3PvEQi.png)

Now, the first one works, and the bottom two do not. And if you click on the fence in  either of the bottom two recipes, they disappear and only the top one is shown. Now, here is the odd part, it is only with the ExtraTrees normal fences, not the Fireproof ones.

![Screenshot](https://i.imgur.com/y8ofjfK.png)

There is only one recipe registered for the fence, it is (acquired via ```/ct recipes```)
```
recipes.addShaped("extratrees:holly_fences", <extratrees:fences.1:2> * 3, [
   [<extratrees:planks.1:2>, <minecraft:stick>, <extratrees:planks.1:2>], 
   [<extratrees:planks.1:2>, <minecraft:stick>, <extratrees:planks.1:2>]
]);
```
------------
### Moving on ###
So, I remove all the fence recipes and add in my own, figuring no worries, when they are removed it will no longer be an issue. Nope. When removed, they all disappear, but when I add mine back in, the ghost ones come back. I even tried removing the non-working recipies explicitly.

#### My Script ####
```
recipes.remove(<extratrees:fences.1:2>);
recipes.removeShapeless(<extratrees:fences.1:2>);
recipes.removeShaped(<extratrees:fences.1:2>, [
    [<extratrees:planks.1:2>,<extratrees:planks.1:2>,<extratrees:planks.1:2>],
    [<extratrees:planks.1:2>,null,                   <extratrees:planks.1:2>]
]);
recipes.addShaped(<extratrees:fences.1:2>, [
    [<extratrees:planks.1:2>,<forestry:oak_stick>,<extratrees:planks.1:2>],
    [<extratrees:planks.1:2>,<forestry:oak_stick>,<extratrees:planks.1:2>]
]);
```
#### The Results ####
![screenshot](https://i.imgur.com/h1cQIXX.png)
-----
#### Versions ####
- Minecraft 1.12.2
- Forge 14.23.2.2624
- JEI 4.8.5.159
- Forestry 5.8.0.250
- BinnieMods 2.5.0.112
- CraftTweaker2 4.1.5
- ModTweaker 4.0.7
- MTLib 3.0.2

**Comment by Nedelosk** [comment]
The two recipes are the recipes for the multi fences. In 1.7.10 binnie used the multi fence recipes to create the default fences and automatically transformed the fence into the default fence to save network data. This is no longer needed because the default fences now have their own recipe. I  removed the automatic transformation into the default fences. There should no longer be any problems with ghost recipes for the default fences.
