### ISSUE TITLE
Frames In Frame Housing Disappear after Relogging

### ISSUE THREAD

**Issue by ncpalmie** [ForestryMC/Binnie#420]
Each time you log off with frames sitting in frame houses on an alveary, the frames disappear, repeated multiple times with the same issue occurring. Also the electric stimulator seems to also be completely unfunctional, but I think there was another issue already opened on that.

Version 1.12.2 2.5.0.110

**Comment by Neemys** [comment]
Same thing happen with alveary mutator, their content disappear.

It does not occur only on relogging but also when you switch world (like nether/overworld) or move far away from an alveary.  (need to wait a bit before it actually disappear)

**Comment by RusTit** [comment]
I can confirm.
As far as I understand, now in the code there is no stage of loading the inventory.
There's only loading the "block" and its type.

**Comment by RusTit** [comment]
I'm not sure that I can fix it myself (I'm new to minecraft modding).
Requires changes in the code:
`binnie/extrabees/alveary/BlockAlveary.java`
