### ISSUE TITLE
The Upgrade path for the bronze compartment dead ends is this intended?

### ISSUE THREAD

**Issue by ProsperCraft** [ForestryMC/Binnie#425]
You can go from wood > copper > bronze

or wood > copper > bronze > iron > gold > diamond

Is the bronze compartment meant to be a dead end and not upgradable to diamond?

**Comment by RusTit** [comment]
As you can read on wiki
https://binnie.mods.wiki/wiki/Compartment
and in code:
https://github.com/ForestryMC/Binnie/blob/f93ad832e18cd8bc7e045e9c1aacae283c814963/core/src/main/java/binnie/core/machines/storage/ModuleStorage.java#L27-L39
so it was the idea of developers.
You can do:
Wood > Copper > Bronze
or
Wood > Copper > Iron > Gold >Diamond
