### ISSUE TITLE
[suggestion] config options for controlling frequency of tree spawns

### ISSUE THREAD

**Issue by xkforce** [ForestryMC/Binnie#427]
It would be nice to be able to control what trees and bushes spawn and the frequency of those spawns natively.

**Comment by temp1011** [comment]
Binnie tree general rate is already controlled in forestry but maybe things should be more granular. Tree configs are more interesting.

**Comment by xkforce** [comment]
Yeah globally the frequency can be controlled but if you want to controll things on a tree by tree level, the only way I've found to do that is with mods like biometweaker which isn't ideal.

**Comment by xkforce** [comment]
Thank you!
