### ISSUE TITLE
Weird visual bugs with TE items after update?

### ISSUE THREAD

**Issue by ncpalmie** [ForestryMC/Binnie#431]
After seeing the new files on curseforge, I closed, updated only binnie's and then re-opened to find these bugs with TE items. Conduits still transfer fluids/energy and the blocks will work again once rotated. Is it possible these are due to the update or was it just super coincidental and I should report it to TE devs? 

Pics: https://imgur.com/a/WZqXK

Purple blocks are TE tanks, and a redstone furnace

Version: 1.12.2-2.5.0.119

**Comment by Nedelosk** [comment]
I don't think binnie is involved in this bug. Seems more like  something you should report to the TE devs.
