### ISSUE TITLE
Crashing during launch when constructing mods

### ISSUE THREAD

**Issue by slav37** [ForestryMC/Binnie#443]
When I launch the technic launcher modpack (ark survival primitive plus) with binnies mods, the mods load; but crashes after the 2/7 mod construction completes. 
[fml-client-latest.log](https://github.com/ForestryMC/Binnie/files/1818439/fml-client-latest.log)

**Comment by temp1011** [comment]
`[18:44:00] [Client thread/ERROR] [FML/]: The mod Forestry (Forestry for Minecraft) requires mod versions [Forge@[10.13.4.1566,)] to be available`

~~Forge version for this pack is outdated. See https://github.com/ForestryMC/ForestryMC/issues/2043. Either update forge or downgrade forestry. This pack dev really needs to update their modpack...~~

Forge is still outdated. Unless you've fixed that based on the other issue. Either way this isn't on Binnie's I think.

**Comment by ProsperCraft** [comment]
Wow, that fml-client-latest.log file is a binary file from ARK

Also, if you are going to submit a file please do it in as a gist http://gist.github.com so we don't have to download it.

And finally, did you add more ram to your modpack, having it stop can indicate you didn't give it enough ram.
