### ISSUE TITLE
Acclimitiser - Lava increases humidity tolerance

### ISSUE THREAD

**Issue by kekvitirae** [ForestryMC/Binnie#445]
Putting lava cans or lava refractory wax capsules in an Acclimatiser will increase humidity tolerance instead of temperature tolerance. Tested with multiple bee types with the same result.

Meadows Bee before: https://i.imgur.com/hrlRzge.png
Meadows Bee during: https://i.imgur.com/PsEbil9.png

All other items increase/decrease their correct tolerance as normal.

Using Binnie's Mods 2.5.0.126

**Comment by Spydrouge** [comment]
I literally can't play a sky-block pack because the only thing we have is lava capsules and I'm supposed to be able to Acclimatize a Wintry bee with temperature tolerance.

**Comment by kekvitirae** [comment]
> I literally can't play a sky-block pack because the only thing we have is lava capsules and I'm supposed to be able to Acclimatize a Wintry bee with temperature tolerance.

This issue was fixed a couple months back. If you're still having issues, I suggest you update the mod.
