### ISSUE TITLE
Can't bottle Lager

### ISSUE THREAD

**Issue by MCEventHorizon** [ForestryMC/Binnie#476]
There are 2 recipes for bottling Lager, Fluid Transposer and Bottler, none of them add fluid to a bottle but they can add it to a can, even tho the recipe shows that it works with bottles.

Using binnie mods 2.5.0.131
Modpack: FTB Revelation 1.7.0

Screenoshots:
![2018-03-25_12 00 25](https://user-images.githubusercontent.com/15619786/37873845-993c12c0-3024-11e8-8744-76781b8c1012.png)
![2018-03-25_12 00 41](https://user-images.githubusercontent.com/15619786/37873846-9ca65920-3024-11e8-8a07-fb96d45bfe5f.png)

**Comment by RusTit** [comment]
@mezz I did a test on the current version (Client), everything works.
![2018-03-25_22 00 34](https://user-images.githubusercontent.com/29846693/37874745-2c2f8cc6-3078-11e8-81d1-14a71f0633be.png)
![2018-03-25_22 00 35](https://user-images.githubusercontent.com/29846693/37874746-2c6049b0-3078-11e8-9f1d-159b808ae483.png)
![2018-03-25_22 00 36](https://user-images.githubusercontent.com/29846693/37874747-2c976a12-3078-11e8-9acd-0d128e1d4cc8.png)
![2018-03-25_22 00 41](https://user-images.githubusercontent.com/29846693/37874748-2ccde8bc-3078-11e8-881d-f37f248b2703.png)
![2018-03-25_22 00 42](https://user-images.githubusercontent.com/29846693/37874749-2d084f66-3078-11e8-8ff5-3ac12231c2ff.png)
![2018-03-25_22 00 43](https://user-images.githubusercontent.com/29846693/37874750-2d4104a0-3078-11e8-912e-01ffff3f5a89.png)

**Comment by Nedelosk** [comment]
@MCEventHorizon You have to use the **Bottle** from binnie and not the **Glass Bottle** from minecraft.

**Comment by RusTit** [comment]
@Nedelosk You're right,
In fact, player can use any, but a universal container for liquids.
And bottles of minecraft are used only for potions.
