### ISSUE TITLE
Fluid duping with shift click into distillery/brewery

### ISSUE THREAD

**Issue by superfluke** [ForestryMC/Binnie#506]
When holding a stackable fluid container (ie the fluid cans from forestry or the wheat mash bottle from binnie), shift clicking the stack with the distillery gui open will insert the fluid but not consume the container. Container is consumed as expected when right clicked on the machine, when picked up and clicked on the fluid input tank and when shift clicking a single item. Steps to reproduce:
1. Have a stack of 2 fermented wheat mash cans
2. Open distillery gui
3. Shift click stack of cans to input unlimited fluid
4. Get drunk

Binnies: binnie-mods-1.12.2-2.5.0.160
Foresty: forestry_1.12.2-5.8.0.263
Forge: 14.23.2.2611

**Comment by nstearns96** [comment]
@Nedelosk This is fixed for me in 1.12.2-2.5.1.201

**Comment by Nedelosk** [comment]
@nstearns96 Thanks
