### ISSUE TITLE
[1.12] Crash when forestry arboriculture module disabled

### ISSUE THREAD

**Issue by Isotab** [ForestryMC/Binnie#515]
My plan was to play without trees or butterflies from forestry and without botany from this but if I try to disable the arboriculture module in forestry this mod causes a crash for botany. I have disabled all modules except extra bees and genetics in the binnie-mods config but that does not help. I would guess the issue is related to #369.

https://pastebin.com/9zRyQDAr

**Comment by temp1011** [comment]
Looks like https://github.com/ForestryMC/ForestryMC/issues/2077 but a different case. Not sure if Forestry or Binnie fault.

**Comment by temp1011** [comment]
Maybe botany should depend on aboriculture. I'm not sure.

**Comment by Isotab** [comment]
Maybe so but I have botany disabled in the config, the point was that it was still loading and crashing as a result

**Comment by Nedelosk** [comment]
The config option to disable the mods is broken. You can currently only disable modules of the mods.

**Comment by xAlicatt** [comment]
Is this being worked on? Will we ever be able to have Binnie's and disable bees or botany or any of the modules without a crash? I really wanted to include this in my pack, but I don't want bees or botany. :(
