### ISSUE TITLE
Papayimar - no recipe and no further info how to get it

### ISSUE THREAD

**Issue by 2hsv4** [ForestryMC/Binnie#521]
As the title says i tried on Avaritia and get stuck on ther ultimate stew bacause the only fruit i cant find or produce or breed is the new Papayimar (blue papaya with glases).
...there are no Papayimar seeds too.
Pls. add a recipe or alternative when implemented in other mods!

**Comment by temp1011** [comment]
Looks like it's commented out in https://github.com/ForestryMC/Binnie/blob/5311933388816defa8897f71ed49ac2fe2f30489/extratrees/src/main/java/binnie/extratrees/genetics/AlleleETFruitDefinition.java#L390 which probably isn't good. Are you playing in a modpack? If so, hasn't the pack maker also experienced this bug?

**Comment by Keridos** [comment]
Also experiencing this on default binnies and avaritia config settings.
