### ISSUE TITLE
[1.7.10]Embittered bees want daylight 

### ISSUE THREAD

**Issue by danielrossyamitrano** [ForestryMC/Binnie#524]
I know there are new versions of both binnie's mods and forestry, but I'm running 1.7.10 alogside other mods for that MC version.
I'm having a weird issue with the embittered bees. The queen wants daylight to breed... in the nether. I found this weird because I didn't have this issue when i tried the same a few years ago (probably with older versions of both forestry and binnie's). If the solution is to backport to an older version, could you tell me to which one?

**Comment by Nedelosk** [comment]
We no longer make updates to the 1.7.10 version of binnies mods.

**Comment by netmc** [comment]
Just in case someone else runs into this thread via Google, the same as I, here is how you work around the issue. If you are running straight Binnie's, you will have to make the alveary, then install alveary lighting in and place the alveary in the nether or use the acclimitizer to add tolerances so it can survive in the overworld. If you are using Gendustry, you can make an industrial apiary with a hell emulation upgrade and place in the overworld, or an industrial apiary with a lighting upgrade and place in the nether, or use the genetic imprinter to add the nocturnal trait to the princess/queen and drone, then breed in the nether.
