### ISSUE TITLE
Lumbermill output does not match JEI

### ISSUE THREAD

**Issue by superfluke** [ForestryMC/Binnie#525]
Best summed up by this screenshot, actual output of 1 log on top, JEI info on bottom:
![image](https://user-images.githubusercontent.com/20022336/39972523-08d52810-56e0-11e8-8808-323df936f5ea.png)

binnie-mods-1.12.2-2.5.0.160
forestry_1.12.2-5.8.0.285
Forge: 14.23.3.2655

**Comment by viveleroi** [comment]
I'm experiencing this too. 

forge-1.12.2-14.23.4.2705
forestry_1.12.2-5.8.0.319
binnie-mods-1.12.2-2.5.0.167
