### ISSUE TITLE
[1.12.2] - Swamp Gum and Douglas Fir lacking in leave blocks

### ISSUE THREAD

**Issue by Spearkiller** [ForestryMC/Binnie#529]
I'm not sure if it's an issue or not, but the default/freshly bred Swamp Gum and Douglas Fir trees when they grow have almost little to no leaves, making them impossible to create more trees without having to actually breed them multiple times (Or in Swamp Gums case, once you plant it you physically cannot plant it again without having to breed more saplings). Once you edit the height aspect through the Genesis you can get them to be taller and have more leaves, but with the low amount of leaves when they're first bred, it would be very hard to breed one that actually looks like a tree and not a tall stump.

For comparison:
Douglas Fir
In game: https://cdn.discordapp.com/attachments/300941293213712385/453072185708380180/unknown.png
In Real Life: https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/A_group_of_Douglas_Firs.jpg/220px-A_group_of_Douglas_Firs.jpg

Swamp Gum
In game: https://cdn.discordapp.com/attachments/300941293213712385/453072229375279104/unknown.png
In Real Life: https://www.southernwoods.co.nz/uploads/Shoppingcart/product-346-2.jpg

Running Binnie Mods 1.12.2-2.5.0.165

**Comment by Nedelosk** [comment]
This site contains images of how they supposed to look. https://binnie.mods.wiki/wiki/Tree_Species
