### ISSUE TITLE
Extra Trees missing nearly everything

### ISSUE THREAD

**Issue by ChillyTiger** [ForestryMC/Binnie#530]
I'm probably missing something here, but I have Forestry installed, as well as Binnie's Mods (from curseforge). I'm using the correct version for my MC version (1.7.10), and I have the latest released from 1.7.10. Nearly everything is missing from Extra Trees (and I'm assuming the rest), as neither the brewery nor anything related to alcohol can be found in the NEI. Am I missing a mod, or is something wrong?

**Comment by KorDum** [comment]
Sorry, but brewery and alcohol were deleted from latest version for 1.7.10, because very buggy. In version for MC 1.12.2 works fine after fixes and refactoring.
