### ISSUE TITLE
[1.7.10] Game crash

### ISSUE THREAD

**Issue by Sackbro17** [ForestryMC/Binnie#532]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: binnie/extrabees/apiary/ItemHiveFrame 

I add a new mod to my mod pack and then this mod crashed while loading the game, so after removing the mode I reloaded it and again the mod crashed.  

Edit: It is not a problem with this mod, but an add on called BinniePatcher Which was causing the problem.  It does not seem to load my worlds though without BinniePatcher so.. Can I delete the Hive Frame and not get any problems or will I? That will corrupt the file omg

**Comment by KorDum** [comment]
Delete Binnie Patcher.
