### ISSUE TITLE
Sub-mods cannot be disabled

### ISSUE THREAD

**Issue by ZXQWAS** [ForestryMC/Binnie#533]
I set B:extraBees=false in binnie-mods.conf, relaunch minecraft, and still see this mod in the list, as well as all the items/bees and their recipes. Also I cannot disable any of these from the mod options menu, I click disable and just nothing happens. Copying this setting to binniecore's main.conf, still don't disable it. I'm playing a modified FTB Continuum.

**Comment by Nedelosk** [comment]
Duplicate of #305
