### ISSUE TITLE
[1.12.2] Marble Hives not spawning

### ISSUE THREAD

**Issue by Boomflex** [ForestryMC/Binnie#535]
Seeing this in:

FTB Revelations v2.0.0 also.

Binnie's Mods: v1.12.2-2.5.0.165

Extrabees main.conf reads

Sets the worldgen spawn chance for marble hives. [range: 0 ~ 10, default: 2]
I:marbleHiveRate=2

**Comment by Nedelosk** [comment]
Duplicate of #274
