### ISSUE TITLE
NullPointerException when Climatizer placed with HWYLA active

### ISSUE THREAD

**Issue by mopsyd** [ForestryMC/Binnie#548]
This is a rehash of an an issue posted on the HWYLA, which turned out to be upstream.

Issue Description:
See stack trace:
https://paste.dimdev.org/owinisosaj.mccrash

This error threw over 1,000 times within two seconds (placed and immediately broke suspect block). It is difficult to tell exactly how many instances of the error occurred, because the log stopped recording due to the volume of them almost immediately.

What happens:
Causes massive volume of NullPointerExceptions, which flood the log beyond the point of being able to capture additional messages. Also causes a huge amount of lag in game (with the Vanilla Fix mod), or immediate crash (without vanilla fix mod).

What you expected to happen:
Expected to be able to place blocks without causing game crashes due to Hwyla failing to render the info for them.

Steps to reproduce:
Place a Climatiser from Binnie's Genetics while Hwyla is installed.
See stacktrace for possible other mods causing conflict.
Affected Versions (Do not use "latest"):
Hwyla: Hwyla-1.8.26-B41_1.12.2.jar
Minecraft: 1.12.2
Forge: 14.23.4.2750
Possible Conflicting Mods (Provide their version, as well)
See provided stacktrace.

Diagnosis from Hwyla team:

Binnie's is returning `true` in `hasCapability(...)` but `null` in `getCapability(...)`

https://github.com/TehNut/HWYLA/issues/126#issuecomment-416070609

**Comment by temp1011** [comment]
This is fixed in the latest version of Binnie's I believe (https://github.com/ForestryMC/Binnie/pull/527)

**Comment by mopsyd** [comment]
Awesome. Is there a release build containing this patch as of yet, or would I need to build from source?

**Comment by temp1011** [comment]
https://minecraft.curseforge.com/projects/binnies-mods/files/2583495 should work
