### ISSUE TITLE
[1.12.2]v2.5.0.b168 Module/mod (Genetics) cannot be disabled

### ISSUE THREAD

**Issue by Cronosus** [ForestryMC/Binnie#551]
Little problem with disabling module/s (not tested all), but genetics cannot be disabled, even i set it to false, its still in game.

**Comment by CrankySupertoonArchive** [comment]
Also this is kind of important because my botany module is crashing and i can not disable it either

https://paste.ee/p/xTEwB

**Comment by CrankySupertoonArchive** [comment]
Sorry if i kind of hijacked this thread.

**Comment by Nedelosk** [comment]
Duplicate of #305
