### ISSUE TITLE
Crash When Using .getIndividual() on Binnie's Bee after the latest version

### ISSUE THREAD

**Issue by TheLimePixel** [ForestryMC/Binnie#561]
So after updating Binnie's to 2.5.1.175 and Forestry to 5.8.2.370, with the mod for my pack I'm getting a crash in the recipes that use Binnie's Bees, such as https://github.com/EmosewaPixel/GregBlockUtilities/blob/1ff712391c580ecf9266f14cc94b1a1eab67eeed/src/main/java/gregblockutils/Recipes/GBRecipeAddition.java#L120
https://pastebin.com/f3m0YMb3

**Comment by Nedelosk** [comment]
Could you please test this again with the newest version after it compiled? http://jenkins.ic2.player.to/job/Binnie's%201.12/176/

**Comment by TheLimePixel** [comment]
It works now, thanks.
