### ISSUE TITLE
Villagers and Blacksmith chests don't spawn in generated chunks.

### ISSUE THREAD

**Issue by Jemsterr** [ForestryMC/Binnie#595]
When travelling to ungenerated chunks (or chunks I deleted in MCEdit for testing purposes), villages spawn empty. No villagers, and no chest in the Blacksmith house.

Removing this mod, deleting the chunks and reloading fixes the issues.  Deleting them again and readding the mod replicates the issue.

I haven't tested dungeon chests yet.

Mods used: Forestry and Binnies. (Both latest releases)

**Comment by temp1011** [comment]
If this only occurs in recent versions it's almost certainly due to https://github.com/ForestryMC/Binnie/pull/579/

**Comment by Jemsterr** [comment]
Looks likely.  Also confirmed that dungeon chests do spawn.

**Comment by nstearns96** [comment]
@Nedelosk After testing to confirm, this issue seems to have been resolved.

**Comment by Nedelosk** [comment]
@nstearns96 Thank you for testing
