### ISSUE TITLE
Banana Trees don't grow their produce

### ISSUE THREAD

**Issue by AlexandraIsabel** [ForestryMC/Binnie#608]
Pack: A Bit of Everything 3.4.0
Version of Forestry: 5.8.2.387
Version of Binnie's Mods: 2.5.1.188
As stated in the title, Banana trees don't grow their produce. Things I have tried to use to make them grow their produce: used a supremium watering can and put the trees into a forestry multifarm set to orchard mode.

**Comment by Danekjovax** [comment]
This may be related to #589

**Comment by NopeDK** [comment]
Can confirm that Banana trees have no produce-leaves.

forestry_1.12.2-5.8.2.394
binnie-mods-1.12.2-2.5.1.188
