### ISSUE TITLE
Please add Lumbermill support for wood from other mods

### ISSUE THREAD

**Issue by lex1975** [ForestryMC/Binnie#62]
Please add Lumbermill support for wood from other mods (TwilightForest, LOTR, Highlands, BoP etc.) or Minetweaker/Crafttweaker (Modtweaker) support.
https://github.com/jaredlll08/CraftTweaker/issues/239
https://github.com/jaredlll08/ModTweaker/issues/496

**Comment by mezz** [comment]
This should be working automatically in the latest versions of Binnie's. Can you confirm?

**Comment by lex1975** [comment]
Yes, working automatically. But make only oak planks from any wood. And some wood (BoP, Highlands)  causes crash.
Test on MC 1.7.10, binnie-mods-1.7.10-2.0.22.7
[crash-2017-11-07_20.09.20-client.zip](https://github.com/ForestryMC/Binnie/files/1450947/crash-2017-11-07_20.09.20-client.zip)

**Comment by mezz** [comment]
Tested on 1.12 and it's working fine.
I guess 1.7.10 needs more work.

**Comment by lex1975** [comment]
Please, take the time to fix this bug. At least for wood from BoP.
