### ISSUE TITLE
Help me plz Game crash

### ISSUE THREAD

**Issue by MoonGhost18** [ForestryMC/Binnie#626]
[game crash report 3.txt](https://github.com/ForestryMC/Binnie/files/4070756/game.crash.report.3.txt)

Got no idea why but since your mod is mentioned i thought you might!

**Comment by g3eky** [comment]
Me too. The exact same stacktrace. Crashed twice. Reverting to the previous version is working fine for me.

**Comment by tezukitty** [comment]
Why was this closed? Still no fix is available. I have the same issue with the exact same stacktrace.
