### ISSUE TITLE
[1.7.10] Crash on sturtup if module Lepidopterology is disabled

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/Binnie#69]
If module Lepidopterology is disabled, shaped recipe for item `Genetics.analyst` invoke crash, because `Mods.Forestry.item("flutterlyzer")` return null.

**Comment by mezz** [comment]
We are no longer supporting the 1.7.10 version but I will accept a PR if you are interested in fixing this issue.

**Comment by KorDum** [comment]
We will not repair in 1.7.10, as there are a lot of modules in the tie on butterflies.
