### ISSUE TITLE
1.11 Plan

### ISSUE THREAD

**Issue by Chocohead** [ForestryMC/Binnie#7]
Are we working on both 1.10 and 1.11 now? Or actively developing 1.11 but only fixing crash bugs on 1.10?

**Comment by mezz** [comment]
I think the project is still too unstable to work on two versions at the same time and I want to focus only on 1.11. 
The changes in 1.11 allow us to do a lot of static analysis with null checks, and I'm doing some refactors to clean up possible null issues right now. It should solve a lot of mysterious bugs that are hard to reproduce, and help make the project less work to maintain in the future.

**Comment by mezz** [comment]
Hm actually giving up on that refactor. It started out well but I started breaking more things with it than I was fixing. There's a lot of stuff in the CraftGui that handles null unsafely but it's very difficult to structure it in a better way without breaking everything else.

**Comment by mezz** [comment]
Let me know if you want/need it on 1.10 and we can figure something out. 
I think that by the time we're all finished and it's ready, 1.12 may be released.

**Comment by Chocohead** [comment]
I think it's probably best we focus on one version, and like you said, 1.10 is only getting older all the time whilst eventually people are going to move on. It'll be nice if I can breed my bees with BC pipes if all goes well ;)
