### ISSUE TITLE
[1.7.10] Enzymes can't be piped out of Incubators with BC pipes

### ISSUE THREAD

**Issue by KocLobster** [ForestryMC/Binnie#72]
I seem unable to pull enzymes out of incubators with BuildCraft pipes. Other types of resources work just fine, like liquid growth medium or bacteria, but Enzymes just stay in the Incubator inventory. Maybe because they are items and not fluids? Maybe there is a problem that causes an issue for items (transport pipes) but not fluids (fluid pipes). Hoppers work just fine too, and have no problem pulling Enzymes out, so the problem seems exclusive to pipes.

**Comment by KorDum** [comment]
@KocLobster
It's work fine. Many info about problem?

**Comment by KorDum** [comment]
Without confirmation and response. Closed.
