### ISSUE TITLE
Separation of Binnie Mods

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/Binnie#75]
Is the plan to separate all 4 mods from another ?

**Comment by mezz** [comment]
The goal of elec is to split off the bee part better so that it's easier to disable, so people can choose these bees or Magic Bees and it can work together better. There is a lot of dependencies between the modules, and it would be cleaner to have some basic modules that only depend on Forestry.

**Comment by mezz** [comment]
I think the mods should still be together in one jar like Forestry does.

**Comment by Nedelosk** [comment]
Ok, good to know.
