### ISSUE TITLE
[1.7.10] Vanilla Wood fence are wrongly named

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/Binnie#78]
Vanilla Wood fence are wrongly named:
![image](https://cloud.githubusercontent.com/assets/2970688/26527082/8cf5c234-438c-11e7-9df8-526c084b23ed.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26527090/a27ae134-438c-11e7-8607-0de4e0e3672b.png)
Spruce wood fence and birch woo fence.

I used the last available self compiled source code from this repo.
Minecraft 1.7.10 Forge 1614

**Comment by KorDum** [comment]
Hm. I don't know, how you get this item, because vanila fence don't crafting from this recipe.
Do you use MineTweaker custom recipes?
![image](https://cloud.githubusercontent.com/assets/1331559/26554257/df11abee-4497-11e7-98ce-a35625507e07.png)

**Comment by Dream-Master** [comment]
Oh yes i see we have minetweaker scripts. So are this items removed or only wrongly named in minetweaker ?

**Comment by KorDum** [comment]
No, ExtraTrees (or Forestry) never added recipes for vanilla planks, only from self-mod.
Do you use https://openeye.openmods.info/mod/binniefencerecipes or similar mod?

**Comment by Dream-Master** [comment]
No i made this recipes a long time ago. Maybe Binnie have thos recipes in a old version.  Are you planing to add it in some future versions?

**Comment by KorDum** [comment]
I can try to do it, but I don't promise.
Too many difficult-scalable code.

**Comment by Dream-Master** [comment]
@KorDum thanks
