### ISSUE TITLE
[1.7.10] Can't add bee gene "Species: Mystical" to the gene bank.

### ISSUE THREAD

**Issue by RegularGuy88** [ForestryMC/Binnie#82]
I'm playing Infinity Evolved: Skyblock v.1.2.0; Genetics version 2.0-pre14; Forestry version 4.2.15.63

I've been trying to add "Species: Mystical" to my gene bank with no success. Issue most likely is caused by the fact that there are 2 different "Mystical" bees - regular one that I got from Botania's Hiveacynth flower (colored orange) and the one you get from crossbreeding Noble and Monastic bees (colored yellow).

I've been trying to add the orange one (from Botania flower).

**Comment by KorDum** [comment]
Have you checked it on new version of Binnie?
Without BinniePatcher including.

**Comment by RegularGuy88** [comment]
Which new version ? IE:S pack has binnie-mods-2.0-pre14. There doesn't seem to be a newer version unless you meant in 1.10.2 or 1.11 pack. If you meant newer game versions - then I haven't tested it there.

Update - I was able to add the other Mystical bee (the crossbread one) to the gene pool without problems.

**Comment by KorDum** [comment]
This is unofficial repo for Binnie. Latest unofficial version can be download from https://ci.bymarcin.com/job/Binnie-Mods-MC1.7.10/

**Comment by RegularGuy88** [comment]
It's the same in the newer version. 

The problem that I noticed is that regular bee can be obtained easily and is used in several mutations+ common and cultivated, but the crossbread bee needs to be made and after that it's not used in any mutations (at least according to NEI) 

If NEI isn't wrong - Why not just transfer all the mutations to the crossbread bee and eliminate the regular one... ? Why are there 2 bees with the same name anyway ?


EDIT - just tested the crossbreeding between regular Mystical and Cultivated in hopes of getting Eldrich - it worked. So it doesn't appear that NEI is wrong. Will test with crossbread Mystical in a while.

**Comment by KorDum** [comment]
Please add new comment to the converstation, not edit. So I will see a notices.

**Comment by RegularGuy88** [comment]
Tried to get Eldrich bee from crossbread Mystical - 10x in a row it didn't work (5x mutators with eyes of ender in them)

Btw - is it intentional that Alveary consumes 5 durability from Oblivion frame and Apiary only 1 per Queen's death ?

**Comment by KorDum** [comment]
> Btw - is it intentional that Alveary consumes 5 durability from Oblivion frame and Apiary only 1 per Queen's death ?

I don't know, need to check in source. Perhaps this is a bug.

> 10x in a row it didn't work (5x mutators with eyes of ender in them)

In original logic impact of mutator have 15% max. You can't chance 100%, only <= 15%.
Please read Issue https://github.com/ForestryMC/Binnie/issues/74

**Comment by RegularGuy88** [comment]
Thank you. Sadly information in most Wiki's is out of date.. :(

**Comment by KorDum** [comment]
> 2 different "Mystical" bees - regular one that I got from Botania's Hiveacynth flower (colored orange) and the one you get from crossbreeding Noble and Monastic bees (colored yellow)

@RegularGuy88 Hmm. I don't see Botania giving at least some bees. Only Binnie Mystical for Botania.
Need info for test.

**Comment by KorDum** [comment]
Without confirmation and response. Closed.
