### ISSUE TITLE
[1.7.10] Stack not found: FORESTRY:beeswax

### ISSUE THREAD

**Issue by Dream-Master** [ForestryMC/Binnie#87]
I tested the lastest code and got this crash. (self compiled)

https://gist.github.com/Dream-Master/2296001641b719e20e6dcd00c28c7f68#file-binnie-crash

Version before the last commit works fine. Did Foresty updates for 1.7.10?
using forestry_1.7.10-4.2.16.64.jar and forge 1614

**Comment by KorDum** [comment]
Yes, I found it too. I do new PR with fix.

**Comment by Dream-Master** [comment]
@KorDum thnaks for fixing stuff in 1.7.10.
