### ISSUE TITLE
[1.11.2]How to build ?

### ISSUE THREAD

**Issue by Valchap** [ForestryMC/Binnie#9]
I try "gradle build" but an error occurs.
Gradle still compiles Binnie.jar into build/libs before planting.
If I wanted to start minecraft with it, the game crash at startup.
The crash log:[crash-2017-04-13_12.53.50-client.txt](https://github.com/ForestryMC/Binnie/files/919273/crash-2017-04-13_12.53.50-client.txt)

**Comment by mezz** [comment]
Nobody has tried running this mod outside of a developer environment yet because it isn't finished, so the build may be broken.
I think what's happening here is an obfuscation error. 
From the crash report it looks l ike `forestry.api.genetics.IAllele#getName` is being changed to something else in the obfuscated environment.

**Comment by Valchap** [comment]
Yes that's it. Thanks. :)

**Comment by Valchap** [comment]
I keep issue open until the mod is playable outside of a developer environment.

**Comment by mezz** [comment]
I fixed the gradle issue, it was very complicated: https://github.com/MinecraftForge/Srg2Source/issues/18
Working on the obfuscation problems now.

**Comment by KorDum** [comment]
Does version 1.11.2 have Jenkins or another CI for auto build (like for 1.7.10)?

**Comment by Valchap** [comment]
Yes, the same as 1.7.10.

**Comment by Nedelosk** [comment]
@KorDum No

**Comment by Nedelosk** [comment]
I haven't seen one.

**Comment by marcin212** [comment]
@KorDum @Nedelosk I can add it to my Jenkins https://ci.bymarcin.com/

**Comment by Nedelosk** [comment]
@marcin212 That would be fantastic.

**Comment by Nedelosk** [comment]
@marcin212 Thank you https://ci.bymarcin.com/job/Binnie-Mods-MC1.11.2/

**Comment by marcin212** [comment]
We need to set up a naming format for compiled binaries of new versions of Binnie's.
https://ci.bymarcin.com/job/Binnie-Mods-MC1.11.2/

**Comment by KorDum** [comment]
By analogy with 1.7.10 I think.
I will do today + README.md

**Comment by KorDum** [comment]
PR https://github.com/ForestryMC/Binnie/pull/83
Done!

**Comment by Valchap** [comment]
Thank you now it work for me. ;)
