### ISSUE TITLE
[1.11.2] Missing textures and models

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/Binnie#91]
- [x] extrabees:misc - all
- [x] extratrees:food - most of them
- [x] extratrees:door - all
- [x] extratrees:fence - all
- [x] extratrees:gate - all
- [x] extratrees:stairs - all
- [x] extratrees:plank - all
- [x] extratrees:slab- all
- [x] binniecore:storage - basic compartment
- [x] genetics:machine - all
- [x] genetics:lab_machine - all

GUI:
- [x] extrabees:textures/gui/processes.png

**Comment by marcin212** [comment]
@Nedelosk @mezz The only block without a texture/model are doors. Forestry's doors look all different. Binnie's will also, or do we just recolor?

**Comment by Nedelosk** [comment]
@marcin212 I prefer that we give every door a diffrent texture. But currently we have no different textures for the doors. So I think we implements them just recolor and if we have later different textures for every door we use them.

**Comment by Nedelosk** [comment]
@marcin212 I have added the doors.
